game_list = [
"Aberrant ",
"Advanced Space Crusade ",
"Adventure",
"Adventure! ",
"Aeon ",
"Aeronautica Imperialis ",
"Aerotech ",
"After the Holocaust",
"Aftermath ",
"AI Web Game ",
"Albion",
"Alien 8 ",
"Alien Logic ",
"Aliens Versus Predator",
"Alone in the Dark ",
"Alpha Centauri ",
"Alpha Omega ",
"Alternate Reality Game",
"Alternity",
"Amazing Engine",
"Anachronox",
"Anarchy Online",
"Anchorhead ",
"Android: Netrunner",
"Andromeda Conquest",
"Angry Birds Space",
"Another World",
"Aquanox ",
"Archimedean Dynasty",
"Archipelago",
"Arctic Baron ",
"ARG ",
"Ark of Captain Blood, The ",
"Arkham Horror",
"Ashen Stars",
"Asteroids",
"Astronaut ",
"Attack Vector: Tactical",
"Autoduel ",
"Awful Green Things from Outer Space, The",
"Azhanti High Lightning ",
"B.A.T.",
"Baen Software ",
"Bargon Attack ",
"Barker, M A R",
"Bastion",
"Battle Command ",
"Battle for Armageddon ",
"Battle Isle ",
"Battle Rider ",
"Battlecruiser 3000 AD",
"Battlecruiser Millenium ",
"Battledroids ",
"Battledrome ",
"Battlefleet Gothic ",
"Battlefleet Mars",
"Battleforce ",
"Battlespace ",
"Battlestar Galactica: The Boardgame",
"Battlesuit ",
"BattleTech",
"Battletroops ",
"Battlezone",
"Beast, The",
"Before Crisis: Final Fantasy VII ",
"Beneath a Steel Sky",
"Berserker Raids ",
"Beyond Good & Evil",
"Beyond the Boundary ",
"Beyond the Stellar Empire",
"Big Eyes, Small Mouth",
"Big Robots, Cool Starships ",
"Bioforge",
"Biohazard ",
"Bioshock",
"Bizarre Adventures of Woodruff and the Schnibble, The ",
"Black Crusade ",
"Blast-Off! ",
"Blaster",
"Blasteroids ",
"Blasto ",
"Blue Dragon ",
"Blue Planet",
"Board Game",
"Bommerz Over Da Sulphur River ",
"Borderlands",
"Bourne Conspiracy, The ",
"Breach ",
"Brilliant Lances ",
"British, Lord ",
"Buck Rogers",
"Buck Rogers in the 25th Century",
"Buck Rogers XXVC",
"Bughunters ",
"Bureau 13 ",
"Call of Cthulhu",
"Captain Blood",
"Car Wars",
"Card Game",
"Carrier Command",
"Castle Falkenstein",
"CCG ",
"Centauri Knights ",
"Challenge ",
"Chamber of the Sci-Mutant Priestess ",
"Champions",
"Changeagents: Out of Control ",
"Chaos Gate ",
"Chess",
"Choose Your Own Adventure",
"Chrono Cross ",
"Chrono Trigger",
"Chronomaster",
"Chrononauts",
"Circuit's Edge",
"City of Heroes",
"City of Villains ",
"Citytech ",
"Clathran Menace, The ",
"Codename: Gordon ",
"Collectible Card Game",
"Collectible Miniatures Game",
"Combat Command ",
"Command & Conquer",
"Commander Blood ",
"Computer Role Playing Game",
"Computer Space ",
"Computer Wargame",
"Conflict: Freespace ",
"Console Role Playing Game ",
"Conspiracy X",
"Continuum: Roleplaying in the Yet",
"Cosmic Encounter",
"Costikyan, Greg",
"Countdown to Doom ",
"Countdown to Doomsday ",
"Crawford, Chris",
"Creature that Ate Sheboygan, The",
"Crescent Hawk's Inception, The ",
"Crescent Hawks' Revenge, The ",
"Crimson Skies",
"Crimson: Steam Pirates ",
"Crisis Core: Final Fantasy VII ",
"Crossroads Adventure ",
"Cryostasis",
"Crysis",
"Cthulhu Live ",
"Cybergeneration ",
"Cyberpunk",
"Cyberpunk 2077",
"Cyberstorm ",
"Cyborg",
"Cytron Masters ",
"d20",
"Daikatana ",
"Damocles ",
"Dark Conspiracy",
"Dark Corners of the Earth ",
"Dark Earth",
"Dark Forces ",
"Dark Future",
"Dark Heresy ",
"Dark Millenium ",
"Dark Nebula ",
"Darkmatter ",
"Darkover",
"Darkspore ",
"Darwinia",
"Dawn of War ",
"Day of the Tentacle ",
"Dead of Winter: A Crossroads Game",
"Dead Space",
"Deadlands",
"Deathwatch ",
"Defender",
"Defiance",
"Delta Green ",
"Descent: Freespace ",
"Designer X ",
"Destroy All Humans!",
"Deus Ex",
"Deus Ex Machina",
"Dig, The",
"Dirge of Cerberus: Final Fantasy VII ",
"Dirtside II ",
"Disco Elysium",
"Dishonored",
"Dissidia: Final Fantasy ",
"Dog Star Adventure ",
"Doom",
"Doom of the Eldar ",
"Doomtown ",
"Dragon ",
"Dreamfall: The Longest Journey ",
"Driller ",
"Duke Nukem 3D ",
"Dune [board game] ",
"Dune [videogame] ",
"Dune 2000 ",
"Dune II: The Building of a Dynasty",
"Dungeons of Dredmor",
"Dust 514 ",
"Dust Tactics ",
"Early American Chrononauts ",
"Earth & Beyond ",
"Earthbound ",
"Earthsiege ",
"Echo Bazaar ",
"Eclipse Phase",
"Elite",
"Emperor: Battle for Dune ",
"Emperor of the Fading Suns ",
"Empire I",
"Empire of the Petal Throne ",
"End of Eternity ",
"Enemy Territory: Quake Wars ",
"Enslaved: Odyssey to the West",
"Epic 40,000 ",
"Etherscope ",
"EVE Online",
"EverQuest ",
"Evil Genius",
"Ex Machina",
"Exile",
"F-Zero ",
"Fading Suns",
"Fahrenheit 451",
"Fallen London",
"Fallout",
"Fate of the World",
"FEAR: First Encounter Assault Recon",
"Federation ",
"Federation and Empire ",
"Federation Commander ",
"Federation Space ",
"Fifth Frontier War ",
"Fighting Fantasy",
"Final Fantasy",
"Final Fantasy: The Spirits Within ",
"Final Liberation ",
"Fire Warrior ",
"First Encounters ",
"First Person Shooter",
"Fish!",
"Flames of Freedom ",
"Forbidden Desert",
"Forbidden Island",
"Force Unleashed, The ",
"Forgotten Futures",
"Fountain of Dreams ",
"Franck, Tyler Corey",
"Freed, Alexander",
"Freedom Force",
"Freelancer",
"Freespace",
"Freeway Warrior ",
"Fringeworthy",
"Front Mission",
"Frontier: Elite II ",
"Frontier: First Encounters ",
"Frozen Synapse",
"FTL: Faster Than Light",
"Full Motion Video",
"Full Throttle",
"Full Thrust",
"Galactic Civilizations",
"Galactic Command: Echo Squad ",
"Galactic Empire",
"Galactic Revolution ",
"Galactic Saga",
"Galactic Starfire ",
"Galactic Trader ",
"Galactos Barrier, The ",
"Galatea ",
"Galaxy Game ",
"Galaxy Trucker",
"Game Design",
"Game-Worlds",
"Gamebook",
"Gamemaster",
"Games",
"Games Magazines",
"Games Workshop",
"Gamma Force in Pit of a Thousand Screams ",
"Gamma Knights ",
"Gamma World",
"Gammarauders ",
"Gardásiyal ",
"Garfield, Richard",
"Garland, Alex",
"Garriott, Richard",
"Gateway Game",
"Gears of War",
"Gene Machine, The",
"GEV ",
"Giants: Citizen Kabuto ",
"Global Resistance ",
"Glory in Death ",
"God Game",
"Godlike",
"Godsfire",
"Golden Heroes",
"Gorkamorka ",
"Great Rail Wars, The ",
"Greenwood, Ed",
"Ground Control ",
"Gun Parade March",
"GURPS",
"Gygax, Gary",
".hack",
"Half-Life",
"Halo: Combat Evolved",
"Hard Nova ",
"Harlan, Thomas",
"Haunted Apiary, The ",
"Heart of the Alien ",
"Heavy Gear",
"Hero System ",
"Heroclix",
"Herzog Zwei ",
"Hitchhiker's Guide to the Galaxy, The",
"Hollow Earth Expedition",
"Holy War",
"Homeworld",
"Horizon Zero Dawn",
"Horus Heresy ",
"Hostile Waters: Antaeus Rising",
"Howard, Jonathan L",
"Hydrofool ",
"Hyperspace",
"Hypertext",
"I Have No Mouth, and I Must Scream",
"I Love Bees ",
"Illuminati",
"Imperial Starfire ",
"Imperium ",
"Imperium Galactica ",
"Independence War: The Starship Simulator",
"Independent Games",
"inFAMOUS",
"Infinite Space",
"Infocomics",
"Inquisitor ",
"Interactive Fiction",
"Interactive Movies ",
"Interactive Narrative",
"Interplanetary ",
"Invasion: Earth ",
"Invasion Orion ",
"Iris ",
"Ironclads and Ether Flyers ",
"Isometric",
"It Came from the Desert",
"Jackson, Shelley",
"Jackson, Steve",
"Jackson, Steve [2]",
"Jedi Knight ",
"John Carter: Warlord of Mars",
"Journeyman Project, The",
"Jovian Chronicles ",
"Judge Dredd [board game] ",
"Judge Dredd: The Role-Playing Game ",
"Justice, Inc",
"Kill Team ",
"King of New York ",
"King of Tokyo",
"Klashball ",
"Knight Hawks ",
"Knights of the Old Republic ",
"Kojima, Hideo",
"Koshan Conspiracy, The ",
"Koster, Raph",
"KULT: The Temple of Flying Saucers",
"Lane Mastodon vs The Blubbermen ",
"Laser Squad",
"Last Battle",
"Last of Us, The",
"Lazarus Project, The ",
"Leather Goddesses of Phobos",
"Left Coast",
"Legions of the Petal Throne ",
"Lego Star Wars ",
"Lensman",
"Live Action Role Playing",
"Living Card Game ",
"Living Legends ",
"Livingstone, Ian",
"Lockjaw ",
"Longest Journey, The",
"Lost Colony ",
"Lost in Time ",
"Lost Odyssey ",
"Lost Patrol ",
"Lunar Lander",
"Machinarium",
"Machinima",
"Majestic",
"Majestic Twelve: The Space Invaders Part IV ",
"Malki !, David",
"Mammon Inc ",
"Manhunter",
"Maniac Mansion",
"Maniac Mansion: Day of the Tentacle",
"Marathon Trilogy",
"Marsport",
"Martian Dreams ",
"Martian Memorandum ",
"Mass Effect",
"Master of Orion",
"Matrix Cubed ",
"Mayday ",
"Mean Streets ",
"Mech Assault ",
"Mech Commander ",
"Mechwarrior ",
"Megatraveller ",
"Megawars ",
"Meier, Sid",
"Mekton",
"Mercenary",
"Merchant of Venus ",
"Meretzky, Steve",
"Metal Gear",
"Metal Gear Solid ",
"Metaltech",
"Metamorphosis Alpha",
"Metro 2033",
"Metroid",
"Metroid Prime ",
"Microsoft Space Simulator",
"Midwinter",
"Miller, Marc",
"Mind Forever Voyaging, A",
"Mindwheel",
"Minion Hunter ",
"Mirror's Edge",
"Missile Command",
"Missionforce: Cyberstorm ",
"Missúm! ",
"MMOG ",
"MMORPG ",
"Molyneux, Peter",
"Morrow Project, The",
"Mother",
"MUD ",
"Mule",
"Multi User Dungeon",
"Multiplayer Battletech ",
"Multiwinia ",
"Mutants and Masterminds",
"My Life with Master",
"Mythos ",
"Necromunda ",
"Nether Earth ",
"Netrunner ",
"Neuromancer",
"Neuroshima ",
"Nexus Ops ",
"Noble Armada ",
"Nomad Soul, The",
"Norco",
"Nuclear Destruction ",
"Nuclear War",
"Obsidian",
"Ogre",
"Olympica",
"Omikron: The Nomad Soul ",
"Once and Future King ",
"Oni",
"Online Worlds",
"Open Gaming License ",
"Orbit",
"Orbiter ",
"Original Flatland Role Playing Game, The ",
"Out of This World",
"Outcast",
"Outer Wilds",
"Outer World ",
"Outer Worlds, The",
"Outpost ",
"Outreach ",
"Overseer ",
"Pandemic",
"Pandora Directive, The ",
"Paranoia",
"Paranoia Complex, The ",
"Parasite Eve ",
"Passion Play ",
"Pathologic",
"PBM ",
"Pegasus Prime ",
"Pepper's Adventures in Time",
"Perfect Dark",
"Perimeter",
"Pestilence: the Utopia ",
"Phantasy Star",
"Phoenix: Beyond the Stellar Empire ",
"Plague, Inc.",
"Plague, Inc: Evolved ",
"Planetfall",
"Planetside ",
"Play by Email",
"Play by Mail",
"Policenauts ",
"Portal",
"Portal [2]",
"Postal Worlds",
"Power Projection ",
"Prime Directive",
"Prisoner of Ice ",
"Privateer ",
"Project Abraham ",
"Project Firestart ",
"Prototype",
"Psi World",
"Psychonauts",
"Qadardálikoi ",
"Quake",
"Queen: The eYe ",
"Quest for the Ancients ",
"Radical Dreamers ",
"Rage",
"Rampage ",
"Reach for the Stars",
"Real Time Strategy",
"Real Time Tactics",
"Rebel Planet ",
"Rebelstar ",
"Red Alert ",
"Red Faction",
"Red vs Blue ",
"Reich Star",
"Remember Me",
"Renegade Legion",
"Renegade: The Battle for Jacob's Star ",
"Rescue at Rigel ",
"Resident Evil",
"Resistance ",
"Resistance: Fall of Man",
"Resistance, The",
"Resonance of Fate",
"Return of the Invaders ",
"Return of the Stainless Steel Rat, The ",
"Return to Eden ",
"Revolution 60",
"Rex: Final Days of an Empire ",
"Rifts",
"Risk 2210 AD",
"Rites of War ",
"Robert Heinlein's Starship Troopers",
"Robert Ludlum's the Bourne Conspiracy ",
"Roborally",
"Robotron 2084",
"Rocket Ranger ",
"Rocketmen: Axis of Evil ",
"Rocketville ",
"Rogue ",
"Rogue Galaxy",
"Rogue Trader ",
"Roguelike",
"Role Playing Game",
"Romero, John",
"RPG ",
"Rules of Engagement ",
"Sakaguchi Hironobu",
"Savage Empire, The ",
"Savage Worlds",
"Sentinel, The",
"Sentinel Worlds",
"Sentinel Worlds I: Future Magic ",
"Sentry, The ",
"Septerra Core: Legacy of the Creator",
"Shadow of Destiny ",
"Shadow of Memories",
"Shadow of the Comet ",
"Shadowrun",
"Shadows of the Empire ",
"Shinseiki Evangelion",
"Ships of the French Arm ",
"Siboot ",
"Sid Meier's Alpha Centauri",
"Silent History, The",
"Silent Running",
"Silicon Dreams",
"Simearth",
"Simonsen, Redmond",
"Simply Cosmic ",
"Sins of a Solar Empire",
"Sky Galleons of Mars ",
"Skyrealms of Jorune",
"SLA Industries",
"Slipstream",
"Smith, Sarah ",
"Snake's Revenge ",
"Snapshot ",
"Snatcher",
"Snowball ",
"Software Toy ",
"Solar Conquest ",
"Soldier's Companion, The ",
"Space",
"Space: 1889",
"Space Ace ",
"Space Channel 5",
"Space Crusade ",
"Space Duel ",
"Space Fleet ",
"Space Hulk ",
"Space Invaders",
"Space Marine ",
"Space Marine Assault ",
"Space Master ",
"Space-O ",
"Space Opera",
"Space Patrol",
"Space Pilot ",
"Space Quest",
"Space Rangers",
"Space Rogue ",
"Space Sim",
"Space Station Oblivion ",
"Space Travel",
"Spacewar",
"Spasim ",
"Spector, Warren",
"Speedball",
"Spore",
"Squad Command",
"Squadron UK",
"Stackpole, Michael A",
"Stalker: Shadow of Chernobyl",
"Stalking the Night Fantastic",
"Star Command ",
"Star Control",
"Star Cruiser",
"Star Fleet Battle Force",
"Star Fleet Battles",
"Star Fleet I: The War Begins",
"Star Fleet Universe",
"Star Frontiers",
"Star General",
"Star Lords",
"Star Munchkin",
"Star Ocean",
"Star Patrol",
"Star Raiders",
"Star Saga",
"Star Ship",
"Star Trader",
"Star Trek Games",
"Star Warrior",
"Star Wars Expanded Universe",
"Star Wars: Galaxies",
"Star Wars Games",
"Star Wars: Knights of the Old Republic",
"Star Wars: The Old Republic",
"Star Wars: Tie Fighter",
"Star Wars: X-Wing",
"Starblade Battalion",
"Starclash II",
"Starcraft",
"Starcross",
"Starcrystal",
"Stardate",
"Stardrive",
"Starfall",
"Starfarers of Catan",
"Starfaring",
"Starfire",
"Starfleet Command ",
"Starfleet Orion",
"Starflight",
"Starforce: Alpha Centauri",
"Stargate",
"Stargrunt II",
"Starlancer",
"Starlord",
"Starmaster",
"Starquest",
"Starship 1",
"Starship Catan",
"Starship Titanic",
"Starship Troopers",
"Starsiege",
"Starsoldier",
"Startopia",
"Starweb",
"Stationfall",
"Stellar Conquest",
"Strange Adventures in Infinite Space",
"Strike Force",
"Strike Team Alpha",
"Striker",
"Succession Wars, The",
"Sundog: Frozen Legacy",
"Sunless Sea",
"Super Metroid",
"Super Star Trek",
"Superhero 2044",
"Supreme Commander",
"Survival Horror",
"Suspended: A Cryogenic Nightmare",
"Sweevo's World ",
"Swords and Glory ",
"Syndicate",
"Syndicate Wars",
"System Shock",
"Tabloid!",
"Tabula Rasa",
"Tawala's Last Redoubt",
"Tékumel",
"Temple of the Beastmen",
"Terror in Meeple City",
"Tex Murphy",
"Third Person Shooter",
"Tie Fighter ",
"Time Zone",
"Timequest",
"To the Moon",
"Tokyo Nova ",
"Torg",
"Total Annihilation",
"Toy Game",
"Trade Wars 2002",
"Trader Trilogy",
"Trail of Cthulhu",
"Transarctica",
"Transhuman Space",
"Traveller",
"Traveller: 2300",
"Tribes",
"Tribes of Crane",
"Tringham, Neal",
"Trinity",
"Triplanetary",
"Triple A",
"Trust and Betrayal: The Legacy of Siboot",
"TSR Inc",
"Twilight: 2000",
"Twilight Imperium",
"Tyranid Attack",
"UFO: Enemy Unknown",
"Ultra Marines",
"Ultra Starfire",
"Under a Killing Moon",
"Underground",
"Universal Combat",
"Universe",
"Unreal",
"Vector 3",
"Vengeance of the Blood Angels",
"VGA Planets",
"Victoriana ",
"Videogame",
"Villains and Vigilantes",
"Voyage of the B.S.M. Pandora",
"Voyager I",
"Walking Dead, The",
"War of Wizards ",
"Wargame",
"Warhammer 40,000",
"Warhammer Warriors ",
"WarpWar ",
"Wasteland",
"Web and Starship",
"Webrunner ",
"Weird Worlds: Return to Infinite Space ",
"Weisman, Jordan ",
"Wendig, Chuck",
"Werewolf",
"Where in the World Is Carmen Sandiego?",
"White Dwarf ",
"Wild Talents",
"Wing Commander",
"Wings out of Shadow",
"Wipeout",
"Woodruff and the Schnibble of Azimuth",
"World of Warcraft ",
"Worlds in Balance",
"Worlds of Ultima",
"Worm in Paradise, The ",
"Wreck of the BSM Pandora ",
"Wright, Will",
"X: Beyond the Frontier ",
"X-Com",
"X Series, The",
"X-Wing ",
"X2: The Threat ",
"X3: Reunion ",
"Xenoblade ",
"Xenoblade Chronicles",
"Xenogears",
"Xenosaga",
"Year Zero",
"Zak McKracken and the Alien Mindbenders",
"Zhodani Conspiracy, The ",
"Zombicide",
"Zombie 15'",
"Zombies, Run!",
"Zone of the Enders "]