movie_list = [
"1 ",
"1 April 2000 ",
"002 Operazione Luna ",
"2 + 5: Missione Hydra",
"... 4 ... 3 ... 2 ... 1 ... Morte",
"4D Man",
"4: Rise of the Silver Surfer",
"5 Centimeters Per Second ",
"6th Day, The",
"7 Faces of Dr Lao",
"9",
"10 Cloverfield Lane ",
"12:01 PM",
"12 Monkeys ",
"12 to the Moon",
"13th Warrior, The ",
"27th Day, The",
"28 Days Later",
"28 Weeks Later ",
"1000 Augen des Dr Mabuse, Die ",
"1,000 Years from Now ",
"1984",
"1984 and Beyond ",
"1990: Bronx Warriors ",
"1990: I Guerrieri del Bronx",
"2001: A Space Odyssey",
"2009: Lost Memories",
"2010",
"2012",
"3000 AD ",
"20,000 Leagues under the Sea",
"20 Million Miles to Earth",
"400 Million Miles from Earth ",
"A.I.: Artificial Intelligence",
"Abbott and Costello Go to Mars",
"Abbott and Costello Meet Dr Jekyll and Mr Hyde",
"Abbott and Costello Meet Frankenstein",
"Abbott and Costello Meet the Invisible Man",
"Abominable Snowman of the Himalayas, The ",
"Abominable Snowman, The",
"About Time",
"Abrahams, Mort",
"Abrams, J J",
"Abre Los Ojos",
"Absent Minded Professor, The",
"Abyss, The",
"Accel World: Infinite Burst ",
"Ad Astra [film]",
"Adam Project, The",
"Adjustment Bureau, The",
"Adolescence of Utena",
"Adventures of Buckaroo Banzai across the 8th Dimension, The",
"Adventures of Captain Marvel",
"Adventures of Stella Star, The ",
"Adventures of the Rocketeer ",
"Aelita",
"Æon Flux",
"Aerial Torpedo, The ",
"After Earth",
"Agent for H.A.R.M.",
"Ai City",
"Airship Destroyer, The",
"Akira",
"Alarm im Weltall ",
"Alien",
"Alien Attack ",
"Alien Contamination ",
"Alien: Covenant",
"Alien Factor, The",
"Alien Nation",
"Alien Resurrection",
"Alien vs Predator ",
"Alien³",
"Aliens [film]",
"Aliens Are Coming, The",
"Aliens from Another Planet ",
"Aliens from Space ",
"Alita: Battle Angel ",
"Alive in Joburg ",
"All Gummed Up",
"Allen, Irwin",
"Alligator",
"Alligator People, The",
"Along the Moonbeam Trail",
"Alpha Incident, The",
"Alphaville",
"Alraune",
"Altered States",
"Altman, Robert",
"Amazing Colossal Man, The",
"Amazing Spider-Man 2, The",
"Amazing Spider-Man, The",
"Amazing Stories [tv]",
"Amazing Transparent Man, The",
"Amazon Women on the Moon ",
"Amazons",
"Ambushers, The",
"American Cyborg: Steel Warrior",
"American International Pictures",
"Anderson, Gerry",
"Anderson, Michael",
"Anderson, Paul W S",
"Anderson, Sylvia ",
"Android [film]",
"Andromeda Nebula, The ",
"Andromeda Strain, The",
"Andromeda the Mysterious ",
"Andy Warhol's Frankenstein ",
"Angel for May, An ",
"Angel Heart ",
"Angels & Demons ",
"Angel's Egg",
"Angry Red Planet, The",
"Aniara ",
"Animal Farm ",
"Animatrix, The",
"Annihilation",
"Anomalisa",
"Another Flip for Dominick ",
"Antena, La",
"Apollo 18",
"Appleseed",
"April 1st, 2000 ",
"April and the Extraordinary World",
"Arachnophobia",
"Armageddon",
"Army of Darkness ",
"Arnold, Jack",
"Aronofsky, Darren",
"Around the World under the Sea",
"Arrival",
"Arrival II ",
"Arrival, The",
"Arrivederci Yamato ",
"Arrivo di Wang, L'",
"Artemis 81",
"Aru Kararu no Isan",
"Assignment Outer Space ",
"Astounding She-Monster, The",
"Astro Boy",
"Astronaut, The",
"Astronauts, The ",
"Astronaut's Wife, The",
"At 3:25 ",
"At the Earth's Core",
"Atlantide, L' ",
"Atlantis: Milo's Return ",
"Atlantis, the Lost Continent",
"Atlantis: The Lost Empire",
"Atom Age Vampire",
"Atom Man vs. Superman ",
"Atomic Brain, The",
"Atomic Kid, The",
"Atomic Man, The ",
"Atomic Monster ",
"Atomic Rulers",
"Atomic Sub, The ",
"Atomic Submarine, The",
"Atragon ",
"Attack from Space",
"Attack of the 50 Foot Woman ",
"Attack of the 50 Ft. Woman",
"Attack of the Blood Leeches ",
"Attack of the Clones ",
"Attack of the Crab Monsters",
"Attack of the Eye Creatures ",
"Attack of the Giant Leeches",
"Attack of the Killer Shrews ",
"Attack of the Killer Tomatoes ",
"Attack of the Mayan Mummy ",
"Attack of the Monsters ",
"Attack of the Mushroom People ",
"Attack of the Puppet People",
"Attack of the Spider Women ",
"Attack the Block",
"Automat Na Přání",
"Avarya",
"Avatar",
"Avengers: Age of Ultron",
"Avengers: Endgame ",
"Avengers: Infinity War",
"Avengers, The [film]",
"AVP Alien vs Predator",
"Aztec Mummy, The",
"Baby: Secret of the Lost Legend",
"Babylon A.D.",
"Back to the Future",
"Back to the Future Part II",
"Back to the Future Part III",
"Bacurau",
"Bad Taste",
"Badham, John",
"Bagi, the Monster of Mighty Nature",
"Bamboo Saucer, The",
"Band, Charles",
"Banlieue 13",
"Barb Wire",
"Barbarella",
"Baron Munchausen ",
"Baron Prášil",
"Barton, Dick ",
"Batman & Mr Freeze: Subzero ",
"Batman and Robin ",
"Batman & Robin [2] ",
"Batman Begins ",
"Batman Beyond: Return of the Joker ",
"Batman Films",
"Batman Forever ",
"Batman: Gotham Knight ",
"Batman – Mask of the Phantasm ",
"Batman: Mystery of the Batwoman ",
"Batman Returns ",
"Batman/Superman Adventures: World's Finest ",
"Batman Superman Movie: World's Finest",
"Batman: Under the Red Hood ",
"Batman vs. Dracula, The ",
"Batman: Year One ",
"Bats",
"*batteries not included",
"Battle Beneath the Earth",
"Battle beyond the Stars",
"Battle beyond the Sun ",
"Battle for Moon Station Dallos ",
"Battle for the Planet of the Apes",
"Battle in Outer Space ",
"Battle: Los Angeles",
"Battle of the Astros ",
"Battle of the Worlds ",
"Battle Royale",
"Battlefield Earth",
"Battleship",
"Battlestar Galactica",
"Bay, Michael",
"Beast from 20,000 Fathoms, The",
"Beast from Haunted Cave",
"Beast Must Die, The",
"Beast of Hollow Mountain, The",
"Beast of Paradise Isle ",
"Beast with 1,000,000 Eyes!, The ",
"Beast with a Billion Backs, The ",
"Beast with a Million Eyes, The",
"Beautiful Women and the Hydrogen Man ",
"Bed-Sitting Room, The",
"Bee and Puppycat",
"Before I Hang",
"Beginning of the End, The ",
"Behemoth, the Sea Monster",
"Being John Malkovich",
"Being There ",
"Below ",
"Bender's Big Score ",
"Bender's Game ",
"Beneath the Darkness ",
"Beneath the Planet of the Apes",
"Bennett, Harve",
"Bermuda Depths, The",
"Bermuda Triangle, The ",
"Betty Boop",
"Beware! The Blob",
"Beyond Bedlam ",
"Beyond Terror ",
"Beyond the Bermuda Triangle",
"Beyond the Time Barrier",
"Beyond the Veil ",
"Bicentennial Man",
"Big Bus, The",
"Big Foot ",
"Big Hero 6",
"Big Man Japan",
"Big Meat Eater",
"Big Mess, The ",
"Bigfoot",
"Bigfoot and the Hendersons ",
"Biggles",
"Bijo to Ekitai-ningen",
"Bill & Ted's Bogus Journey ",
"Bill & Ted's Excellent Adventure",
"Billion Dollar Brain ",
"Biohazard: Genesis ",
"Bird in the Head, A",
"Birds, The",
"Birth",
"Birth of Frankenstein ",
"Black Friday",
"Black Hole, The",
"Black Moon Rising ",
"Black Panther",
"Black Scorpion, The",
"Black Sleep, The",
"Black Sun, The ",
"Black Werewolf ",
"Blade Runner",
"Blade Runner 2049",
"Blaisdell, Paul",
"Blind Bargain, A",
"Blindness",
"Bliss: The Film ",
"Blob Returns, The ",
"Blob, The",
"Blomkamp, Neill",
"Blood Beast from Outer Space ",
"Blood Beast Terror, The",
"Blood Creature ",
"Blood Freaks ",
"Blood Island ",
"Blood of Fu Manchu, The ",
"Blood of the Vampire",
"Blood of the Werewolf ",
"Blood on His Lips ",
"Blue Little Bear Ursa Minor Blue",
"Blue Sunshine",
"Blue Thunder",
"Blueprint ",
"Body in the Web, The ",
"Body Snatchers",
"Bomba Films",
"Book of Eli, The",
"Boorman, John",
"Booth, Walter R",
"Born in Flames",
"Bourbon Street Shadows ",
"Bourne Films",
"Bourne Identity, The ",
"Bourne Legacy, The ",
"Bourne Supremacy, The ",
"Bourne Ultimatum, The ",
"Box, The",
"Boy and His Dog, A",
"Boy with Green Hair, The",
"Boys from Brazil, The",
"Brain Dead",
"Brain Eaters, The",
"Brain from Planet Arous, The",
"Brain Snatchers, The ",
"Brain that Wouldn't Die, The ",
"Brain, The ",
"Braindead ",
"Brainstorm",
"Brave Little Toaster Goes to Mars, The ",
"Brave Little Toaster, The ",
"Brazil [film]",
"Brewster McCloud",
"Brick Bradford",
"Brick Bradford [film] ",
"Bride of Frankenstein, The",
"Bride of Re-Animator ",
"Bride of the Incredible Hulk ",
"Bride, The ",
"Brides of Fu Manchu, The ",
"Briggs, Andy",
"Bronx Warriors ",
"Bronx Warriors 2 ",
"Brood, The",
"Brooks, Mel",
"Brother from Another Planet, The",
"Brothers of the Head ",
"Brothers Strause, The ",
"Bruce Gentry: Daredevil of the Skies",
"Bubble E Go! Time Machine Wa Drum-Shiki",
"Bubble Fiction: Boom Or Bust ",
"Bubble, The",
"Bubble Trouble",
"Buck Rogers ",
"Buck Rogers in the 25th Century",
"Buckner, Robert",
"Bug",
"Buried Alive ",
"Burton, Tim",
"Butterfly Effect, The",
"By Dawn's Early Light",
"By Rocket to the Moon ",
"Bye-Bye Jupiter ",
"Byōsoku 5cm ",
"Caballero del Dragón, El ",
"Cabin in the Woods, The",
"Cactus Makes Perfect",
"Calculator",
"California Man ",
"Caltiki, the Immortal Monster",
"Cameron, James",
"Cantwell, Colin",
"Cape Canaveral Monsters, The",
"Capricorn One",
"Captain America",
"Captain America: Civil War",
"Captain America: The First Avenger",
"Captain America: The Winter Soldier",
"Captain Midnight",
"Captain Nemo and the Underwater City",
"Captain Scarlet and the Mysterons",
"Captain Video",
"Captive Wild Woman",
"Captive Women",
"Caravan of Courage ",
"Carnage",
"Carne Per Frankenstein ",
"Carnosaur",
"Carolina Cannonball",
"Carpenter, John",
"Carrie",
"Carrie 2 ",
"Carruth, Shane",
"Cars that Ate Paris, The",
"Case for the Rookie Hangman ",
"Casino Royale ",
"Casshan",
"Castle in the Sky ",
"Castle of Fu Manchu, The ",
"Cat from Outer Space, The",
"Cat Soup",
"Cat-Women of the Moon",
"Catching Fire ",
"Catfight",
"Cell, The",
"Cells at Work!",
"Cendrars, Blaise",
"CFQ ",
"Chairman, The ",
"Chambers, John",
"Chang Cheng ",
"Change of Mind",
"Chapman, Graham ",
"Chappie",
"Charleston Parade ",
"Charly",
"Cherez Ternii – K Zvyozdam",
"Chikyū Bōeigun",
"Chikyu Saidai no Kessan ",
"Children of Men",
"Children of the Damned",
"Children Who Chase Lost Voices",
"China Syndrome, The",
"Chitty Chitty Bang Bang ",
"Chosen Survivors",
"Chronicle [film]",
"Chronicles of Riddick: Dark Fury, The ",
"Chronicles of Riddick, The",
"Chronopolis",
"Chubbchubbs, The",
"Cinema",
"Circle, The",
"City Beneath the Sea",
"City in the Sea ",
"City Limits",
"City of Ember",
"Clair, René",
"Clan of the Cave Bear, The ",
"Class of 1999",
"Class of 1999 II: The Substitute ",
"Classic War of the Worlds, The ",
"Cleese, John ",
"Clockwork Orange, A",
"Clone [film] ",
"Clone Master, The",
"Clone: The Man Who Gave Birth to Himself ",
"Clones, The",
"Clonus ",
"Close Encounters of the Fourth Kind: Infestation from Mars ",
"Close Encounters of the Third Kind",
"Close Encounters of the Third Kind – The Special Edition",
"Cloud Atlas",
"Cloud of Andromeda, The ",
"Cloudy with a Chance of Meatballs",
"Cloudy with a Chance of Meatballs 2",
"Cloverfield",
"Cobb, Ron",
"Cocoon",
"Cocoon: The Return ",
"Code 46",
"Code Hunter ",
"Code Name Trixie ",
"Coen, Franklin",
"Cohen, Larry",
"Cold Equations, The",
"Cold Night's Death, A",
"Collision Course ",
"Colossus of New York, The",
"Colossus, the Forbin Project",
"Coma",
"Commando Cody ",
"Commando Cody: Sky Marshal of the Universe",
"Communion",
"Conan the Destroyer ",
"Coneheads",
"Congo ",
"Congress, The",
"Conquest of Space",
"Conquest of the Deeps ",
"Conquest of the Earth ",
"Conquest of the Planet of the Apes",
"Conquistador de la Luna",
"Contact",
"Contact [2]",
"Contagion",
"Contamination ",
"Contamination: Alien Arriva Sulla Terra",
"Contract",
"Conway, Gerard F",
"Cooper, Merian C",
"Coraline ",
"Core, The",
"Corman, Roger",
"Cosmic Man, The",
"Cosmic Monster, The ",
"Cosmic Princess ",
"Cosmic Voyage, The ",
"Cosmonauts on Venus ",
"Cosmopolis",
"Countdown",
"Countdown: The Sky's on Fire",
"Counterblast",
"Counterpoint ",
"Cowboy Bebop",
"Cowboy Bebop: Tengoku no Tobira ",
"Cowboys & Aliens",
"Cox, Alex",
"Crack in the World",
"Crackle of Death",
"Crash ",
"Crawling Eye, The ",
"Crawling Hand, The",
"Crawling Monster, The ",
"Crazies, The",
"Crazy Ray, The ",
"Creature",
"Creature from Another World, The ",
"Creature from Black Lake",
"Creature from the Black Lagoon, The",
"Creature from the Cave ",
"Creature from the Haunted Sea",
"Creature Walks Among Us, The",
"Creature with the Atom Brain",
"Creeping Terror, The",
"Creeping Unknown, The ",
"Cremators, The",
"Crichton, Michael",
"Crime Zone ",
"Crimes of the Future",
"Criminali della Galassia, I",
"Crimson Pirate, The",
"Critters",
"Critters 2: The Main Course ",
"Critters 3 ",
"Critters 4: Critters in Space ",
"Croisières Sidérales",
"Cronenberg, David",
"Cronocrímenes, Los",
"Crouching Tiger, Hidden Dragon ",
"Crow, The",
"Crusher Joe",
"Cube",
"Curse of Frankenstein ",
"Curse of the Aztec Mummy, The",
"Curse of the Fly",
"Curse of the Werewolf, The ",
"Cybernetic Grandma, The",
"Cyborg 009",
"Cyborg 2087",
"Cyclops, The",
"Cypher",
"D.A.R.Y.L.",
"D-Day on Mars ",
"Da Vinci Code, The ",
"Dai-sanji sekai taisen: Yonjû-ichi jikan no kyôfu ",
"Daikaijū Gamera",
"Daikaijū Kuchusen ",
"Daikatana ",
"Daleks: Invasion Earth 2150 A.D.",
"Damnation Alley",
"Damned, The",
"Danger: Diabolik ",
"Danger Vient de l'Espace, Le ",
"Dangerous Island ",
"Dante 01",
"Dante, Joe",
"Daredevil",
"Dark Angel [film] ",
"Dark City",
"Dark Knight Rises, The ",
"Dark Knight, The ",
"Dark Star",
"Dark Sun ",
"Dark, The ",
"Darker Side of Terror, The",
"Darkman",
"Daughter of Destiny ",
"Daughter of Dr Jekyll, The",
"Davison, Peter",
"Dawn of the Dead",
"Dawn of the Planet of the Apes",
"Day After, The",
"Day After Tomorrow, The",
"Day Mars Invaded Earth, The",
"Day of the Animals, The",
"Day of the Dead",
"Day of the Dolphin, The",
"Day of the Triffids, The",
"Day the Earth Caught Fire, The",
"Day the Earth Stood Still, The",
"Day the Fish Came Out, The",
"Day the Sky Exploded, The ",
"Day the World Ended",
"Day Time Ended, The",
"Daybreakers",
"DC Cinematic Universe ",
"DC Extended Universe",
"de Chomón, Segundo",
"Dead Kids",
"Dead Leaves",
"Dead Man Running ",
"Dead Zone, The",
"Deadly Bees, The",
"Deadly Harvest",
"Deadly Invention, The ",
"Deadly Mantis, The",
"Deadly Ray from Mars, The ",
"Death and Rebirth ",
"Death from Outer Space ",
"Death Line",
"Death of the Incredible Hulk ",
"Death Race",
"Death Race 2000",
"Death Watch ",
"Deathsport ",
"Decima Vittima, La",
"Deep Blue Sea",
"Deep Impact",
"Deepstar Six",
"Def-Con 4",
"Déjà Vu",
"Del Toro, Guillermo",
"Delicatessen",
"Delta Space Mission",
"Deluge",
"Demolition Man",
"Demon ",
"Demon and the Mummy, The ",
"Demon Seed",
"Demon Within, The ",
"Demons of the Swamp ",
"Dennō Coil",
"Dernier Combat, Le",
"Designated Mourner, The ",
"Despicable Me",
"Despicable Me 2 ",
"Destination Inner Space",
"Destination Moon",
"Destination Moonbase-Alpha ",
"Destination Saturn ",
"Destination Space",
"Destroy All Monsters ",
"Destroy All Planets ",
"Devil Bat, The",
"Devil-Doll, The",
"Devil Girl from Mars",
"Devilman Crybaby",
"Devil's Plot ",
"Diabolic Invention, The ",
"Diabolical Dr Mabuse, The ",
"Diabolik",
"Diafanoidi Portano de Morte, I ",
"Diafanoidi Vengono la Morte, I",
"Diary of Tortov Roddle, The",
"Diavoli della Spazio, I ",
"Dick Barton at Bay ",
"Dick Barton Strikes Back",
"Diebuster ",
"Digby, the Biggest Dog in the World ",
"Dimension 5",
"Dimension Four ",
"Dinosaur Island ",
"Dinosaurus!",
"Disappearance of Flight 412, The",
"Disappearance of Haruhi Suzumiya, The",
"Disaster in Time",
"Discovery of Heaven, The ",
"Disney, Walt ",
"District 13 ",
"District 9",
"Divide, The",
"DOA: Dead Or Alive ",
"Doc Savage: The Man of Bronze",
"Dr Cadman's Secret ",
"Dr Cyclops",
"Dr Jekyll and Mr Hyde",
"Dr Jekyll and Mrs Hyde ",
"Dr. M",
"Dr Mabuse, der Spieler",
"Dr Mabuse the Gambler ",
"Dr Mabuse vs Scotland Yard ",
"Dr No",
"Dr Renault's Secret",
"Dr Satan",
"Dr Satán y la Magia Negra",
"Doctor Strange",
"Dr. Strangelove Or: How I Learned to Stop Worrying and Love the Bomb",
"Dr Who and the Daleks",
"Doctor X",
"Donner, Richard",
"Donnie Darko",
"Donovan's Brain",
"Don't Look Up",
"Doom [film] ",
"Doomsday Machine",
"Doomwatch",
"Dopey Dicks",
"Doppelganger",
"Doroga k Zvezdam",
"Dos Cosmonautas a la Fuerza",
"Dracula vs Frankenstein",
"Dragon's Heaven",
"Dream Come True, A ",
"Dream Machine, The ",
"Dreamcatcher",
"Dreams of an Astronomer ",
"Dreamscape",
"Dredd",
"Duel",
"Duel of the Space Monsters ",
"Dune",
"Dune: Part One",
"Dune Rollers ",
"E.T.: The Extra-Terrestrial",
"Earth Defense Force ",
"Earth Dies Screaming, The",
"Earth Girls Are Easy",
"Earth II",
"Earth Star Voyager",
"Earth to Echo",
"Earth vs. the Flying Saucers",
"Earth vs the Spider",
"Earthquake",
"Earth's Final Fury ",
"Ebirah, Horror of the Deep ",
"Ed Wood ",
"Eden Formula, The ",
"Eden Log",
"Eden of the East",
"Edgar, Alfred",
"Edge of Darkness",
"Edge of Tomorrow",
"Edo Ni Awareta King Kong ",
"Ego Trip ",
"Eight Legged Freaks",
"Electronic Monster, The ",
"Element of Crime, The",
"Eliminators",
"Ellis, Lindsay",
"Elysium",
"Embryo",
"Emmerich, Roland",
"Empire of Corpses, The",
"Empire of the Ants",
"Empire Strikes Back, The ",
"Emsh, Ed ",
"Emshwiller, Ed",
"Encino Man",
"Encounter at Raven's Gate ",
"Encounter in Space ",
"End of August at the Hotel Ozone, The ",
"End of Evangelion, The ",
"End of the World [film] ",
"End of the World, The [film] ",
"End of the World, The [film 2]",
"Endangered Species",
"Ender's Game",
"Endless, The",
"Enemy from Space ",
"Enemy Mine",
"Enemy Within, The ",
"England Invaded",
"Equilibrium",
"Escape from Absalom ",
"Escape from LA",
"Escape from New York",
"Escape from Planet Earth ",
"Escape from the Planet of the Apes",
"Escape of Megagodzilla, The ",
"Escape to Witch Mountain ",
"Eternal Sunshine of the Spotless Mind",
"Étrange Aventure de Lemmy Caution, Une ",
"Europa Report",
"Evangelion 1.0: You Are (Not) Alone ",
"Evangelion 2.0: You Can (Not) Advance ",
"Eve of Destruction",
"Event Horizon",
"Everything Everywhere All at Once",
"Everything You Always Wanted to Know About Sex (But Were Afraid to Ask)",
"Evil Brain from Outer Space",
"Evil Dead, The ",
"Evil Force, The ",
"Evil of Frankenstein, The ",
"Ewok Adventure, The",
"Ewoks: The Battle for Endor ",
"Ex Machina [film]",
"Excursion dans la Lune",
"Excursion to the Moon ",
"eXistenZ",
"Exo-Man",
"Expedition Moon ",
"Exploits of Elaine, The",
"Explorers",
"Extraordinary Adventures of Saturnino Farandola, The",
"Eyes Without a Face ",
"F.P.1 Antwortet Nicht",
"F.P.1 Doesn't Answer",
"Fabulous Baron Munchausen, The ",
"Fabulous World of Jules Verne, The ",
"Face of Fu Manchu, The",
"Faculty, The",
"Fahrenheit 451",
"Fail Safe",
"Falls, The",
"Fantastic Four",
"Fantastic Invasion of Planet Earth ",
"Fantastic Planet ",
"Fantastic Puppet People, The ",
"Fantastic Voyage",
"Farr, David",
"Fatherland",
"Favreau, Jon",
"Felix the Cat",
"Fever, The ",
"Field of Dreams",
"Fiend Without a Face",
"Fifth Element, The",
"Fight Club ",
"Figures in a Landscape ",
"Film ",
"Film Serials ",
"Fin du Monde, La",
"Final Countdown, The",
"Final Programme, The",
"Final War, The ",
"Fire and Ice ",
"Fire in the Sky",
"Fire in the Sky, A",
"Fire Maidens from Outer Space ",
"Firefly",
"Firefox",
"Firestarter",
"First Man Into Space",
"First Men in the Moon",
"First Spaceship on Venus ",
"First Woman into Space ",
"Five",
"Five Fingers of Death ",
"Five Million Years to Earth ",
"Five Minutes to Zero ",
"Flame Barrier, The",
"Flash Gordon",
"Flash Gordon Conquers the Universe ",
"Flash Gordon: Space Soldiers Conquer the Universe ",
"Flash Gordon's Trip to Mars ",
"Fleisch ",
"Fleischer, Max",
"Flesh Eaters, The",
"Flesh for Frankenstein ",
"Flesh Gordon",
"Flight of the Navigator",
"Flight to Mars",
"Flintstones in The Man Called Flintstone, The ",
"Flintstones, The",
"Flipside of Dominick Hide, The",
"Flowers for Algernon",
"Fly II, The",
"Fly, The",
"Flying Disc Man from Mars",
"Flying Saucer Daffy",
"Flying Saucer Mystery, The",
"Flying Saucer, The",
"Flying Serpent, The",
"Food of the Gods",
"Footprints on the Moon",
"Forbidden Planet",
"Forbidden World",
"Forbin Project, The ",
"Forever Young",
"Forgotten, The",
"Fortress",
"Found Footage",
"Fountain, The",
"Four-Sided Triangle",
"Fourth Kind, The",
"Frankenheimer, John",
"Frankenstein",
"Frankenstein 1970",
"Frankenstein 1975 ",
"Frankenstein and the Monster from Hell ",
"Frankenstein Created Woman ",
"Frankenstein Meets the Space Monster ",
"Frankenstein Meets the Spacemonster",
"Frankenstein Meets the Wolfman ",
"Frankenstein Must Be Destroyed ",
"Frankenstein: The True Story ",
"Frankenstein Unbound",
"Frankenstein's Daughter",
"Frankenweenie",
"Frau im Mond, Die",
"Freedom: The Voice from Ein Harod ",
"Freejack",
"Freiberger, Fred",
"Friday the Thirteenth ",
"Fright Night ",
"Frogs",
"From Beyond",
"From the Drain",
"From the Earth to the Moon",
"Frozen Alive",
"Fu Manchu",
"Fuelin' Around",
"Fuga Dal Bronx ",
"Fugitive Futurist, The",
"Fukkatsu no Hi",
"Fullmetal Alchemist: Brotherhood",
"Fulton, John P",
"Fungus of Terror ",
"Fury, The",
"Fushigi no Umi no Nadia ",
"Futurama",
"Future Cop ",
"Future Cop 2 ",
"Future Shock ",
"Future Woman ",
"Futureworld",
"Gabriel Over the White House ",
"Gainax",
"Gake no Ue no Ponyo ",
"Galaxina",
"Galaxy Express 999",
"Galaxy of Terror ",
"Galaxy Quest",
"Gall Force: Eternal Story",
"Game, The ",
"Gamer",
"Gamera",
"Gamma 3: Cosmic War ",
"Gamma People, The",
"Gamma Quadrilogy",
"Gandahar",
"Garaga",
"Gargon Terror, The ",
"Gargoyles",
"Garland, Alex",
"Garnett, Tay",
"Gas-s-s-s, Or It Became Necessary to Destroy the World ...",
"Gasaraki ",
"Gattaca",
"Gene Autry and the Phantom Empire ",
"Genesis II",
"Genie, Das ",
"Get Smart!",
"Getter Robo ",
"Ghidorah Sandai Kaiju Chikyu Saidai no Kessan ",
"Ghidrah, the Three-Headed Monster ",
"Ghost in the Shell",
"Ghost of Frankenstein ",
"Ghost of Slumber Mountain, The",
"Ghostboat ",
"Ghosts of Mars",
"Giant Behemoth, The ",
"Giant Claw, The",
"Giant Claws ",
"Giant from Devil's Crag ",
"Giant from the Unknown",
"Giant Gila Monster, The",
"Giant Leeches, The ",
"Giant Spider Invasion, The",
"Gift from a Red Planet ",
"Gigantes Interplanetarios ",
"Gigantes Planetarios",
"Gigantis ",
"Gigantis the Fire Monster ",
"Gill Woman ",
"Gilliam, Terry",
"Girl from Rio, The ",
"Girl in the Moon, The ",
"Girl of Time, The ",
"Girl Who Cut Time, The ",
"Girl Who Leapt Through Time, The ",
"Girl Who Saved the World, The ",
"Gladiator, The ",
"Gladiatorerna",
"Gladiators, The ",
"Glassy Ocean",
"Glen and Randa",
"Gnome-Mobile, The ",
"God Told Me To",
"Godzilla",
"Gog",
"Gojira",
"Gojira 1985",
"Goke, Body Snatcher from Hell",
"Gold",
"Golden Bat, The",
"Golden Compass, The ",
"Goliath Awaits",
"Gorath ",
"Gordon, Bert I",
"Gordon, Stuart [2]",
"Gorgo",
"Gotham Girls",
"Grand Tour: Disaster in Time ",
"Gravity [film]",
"Great Wall, The",
"Green Goddess, The ",
"Green Hornet, The",
"Green Lantern",
"Green Mansions ",
"Green Slime, The",
"Gremlins ",
"Grey",
"Grosse Verhau, Der",
"Groundhog Day",
"Groundstar Conspiracy, The",
"Guardians of the Galaxy",
"Guardians of the Galaxy Vol. 2",
"Guerre Planetari ",
"Gulliver",
"Gulliver's Travels ",
"Gunbuster ",
"Gundam ",
"Gunparade March: The New March ",
"Gunparade Orchestra ",
"Gwen, or the Book of Sand",
"H G Wells' Empire of the Ants ",
"H.G. Wells' The War of the Worlds ",
"H-Man, The ",
"Half Human",
"Halloween III: Season of the Witch",
"Hammond Monster, The ",
"Hamster Factor and Other Tales of Twelve Monkeys, The ",
"Hand of Death",
"Handmaid's Tale, The",
"Hands of a Stranger ",
"Hands of a Strangler ",
"Hands of Orlac, The ",
"Hangar 18",
"Hanna",
"Hanna-Barbera",
"Happening, The",
"Happiness Cage, The ",
"Happytime Murders, The",
"Hard to Be a God ",
"Hardcore Henry",
"Hardware",
"Harry and the Hendersons",
"Harryhausen, Ray",
"Haskin, Byron",
"Haunted Palace, The ",
"Haunting, The ",
"Hauru no Ugoku Shiro",
"Hauser's Memory",
"Have Rocket, Will Travel",
"Hawk of the Wilderness ",
"Head, The",
"Heartbeeps",
"Heaven Ship, The ",
"Heavens Call, The ",
"Heavy Metal",
"Hell Fire ",
"Hellfire ",
"Hellstrom Chronicle, The",
"Her",
"Hercules against the Moon Men ",
"Herrin von Atlantis, Die",
"Hertzler, J G",
"Hidden, The",
"Hideous Sun Demon, The",
"High Life",
"High-Rise",
"High Treason",
"Highlander ",
"Highlander II: The Quickening",
"Himmelskibet",
"Hitch Hiker's Guide to the Galaxy, The",
"Hitchcock, Alfred",
"Hollow Man",
"Hollywood Boulevard ",
"Holy Motors",
"Homunculus",
"Homunculus der Führer ",
"Honey, I Blew Up the Kid ",
"Honey, I Shrunk the Kids",
"Horror! ",
"Horror Chamber of Dr Faustus, The ",
"Horror Express ",
"Horror of Frankenstein, The ",
"Horrors of Spider Island",
"Horrors of the Red Planet ",
"Hoshi no Koe ",
"Host, The",
"Hot Stuff",
"Hotel Transylvania ",
"Hounds of Zaroff ",
"House of Frankenstein",
"House of Fright ",
"House of Monsters ",
"House of Small Cubes, The ",
"How I Live Now",
"How Science Fiction Viewed the Moon ",
"Howl no Ugoku Shiro ",
"Howling, The ",
"Howl's Moving Castle ",
"Hudson Hawk ",
"Hugo [film] ",
"Hulk",
"Human Nature",
"Human Vapour, The",
"Humanoid Woman ",
"Humanoids from the Deep",
"Hume, Cyril",
"Hunger Games, The",
"Hunger Games, The: Catching Fire",
"Hurd, Gale Anne",
"Hyams, Peter",
"Hydrozagadka",
"I Am Number Four",
"I Come in Peace",
"I Love Maria",
"I Married a Monster from Outer Space",
"I, Robot",
"I Was a Teenage Frankenstein",
"I Was a Teenage Gorilla ",
"I Was a Teenage Werewolf",
"Icarus XB-1 ",
"Ice Pirates, The",
"Iceman",
"Idaho Transfer",
"Igor",
"Ikarie XB-1",
"Ikeda Kenshō ",
"Ikeda Noriaki",
"Illustrated Man, The",
"I'm a Monkey's Uncle",
"Immediate Disaster ",
"Impossible Voyage, An ",
"Impostor",
"In Like Flint",
"In the Year 2889 ",
"In Time",
"Inception",
"Incident at Raven's Gate",
"Incredible Hulk, The",
"Incredible Melting Man, The",
"Incredible Petrified World, The",
"Incredible Shrinking Man, The",
"Incredible Shrinking Woman, The ",
"Incredible Two-Headed Transplant, The ",
"Incredibles, The",
"Independence Day",
"Indestructible Man",
"Indiana Jones and the Kingdom of the Crystal Skull",
"Indiana Jones and the Last Crusade ",
"Indiana Jones and the Temple of Doom ",
"Inland Empire",
"Innerspace",
"International Crime ",
"Interstella 5555",
"Interstellar",
"Into Pitch Black ",
"Into the Primitive ",
"Into the Wild Green Yonder ",
"Intrigue, The ",
"Invader Zim: Enter the Florpus",
"Invaders from Mars",
"Invaders from Space",
"Invaders from the Deep ",
"Invasion [film]",
"Invasion Earth 2150 AD ",
"Invasion Force ",
"Invasion from Inner Earth",
"Invasion of Astro-Monster ",
"Invasion of Mars ",
"Invasion of Planet X ",
"Invasion of the Bee Girls",
"Invasion of the Body Snatchers",
"Invasion of the Flying Saucers ",
"Invasion of the Gargon ",
"Invasion of the Hell Creatures ",
"Invasion of the Neptune Men",
"Invasion of the Saucer Men",
"Invasion of the Star Creatures",
"Invasion, The",
"Invasion U.S.A.",
"Invention of Destruction ",
"Invenzione di Morel, L' ",
"Invisible Agent, The ",
"Invisible Avenger",
"Invisible Avenger, The",
"Invisible Boy, The",
"Invisible Man Appears, The",
"Invisible Man Returns, The ",
"Invisible Man, The",
"Invisible Man vs. The Human Fly, The",
"Invisible Man's Revenge, The ",
"Invisible Ray, The",
"Invisible Woman, The ",
"Iria: Zeiram the Animation",
"Iron Giant, The",
"Iron Man",
"Iron Man 2",
"Iron Man 3",
"Iron Sky",
"Island at the Top of the World, The",
"Island City",
"Island Claws",
"Island of Dr Moreau, The",
"Island of Lost Souls",
"Island of Lost Women",
"Island of Mutations ",
"Island of Terror",
"Island of the Burning Damned ",
"Island of the Lost",
"Island, The",
"Isle of Lost Ships, The ",
"Isola degli Uomini Pesce, L'",
"It Came from Beneath the Sea",
"It Came from Outer Space",
"It Conquered the World",
"It Fell from the Flame Barrier ",
"It Happened Here",
"It Happened Tomorrow",
"It Lives Again",
"It! the Terror from beyond Space",
"It's a Bird! It's a Plane! It's Superman! ",
"It's Alive",
"It's Alive II ",
"It's Alive III: Island of the Alive ",
"It's Hot in Paradise ",
"Izbavitelj ",
"James Bond ",
"Je T'aime, Je T'aime",
"Jekyll's Inferno ",
"Jennings, Gordon",
"Jennings, Humphrey",
"Jerome Bixby's The Man from Earth",
"Jetée, La",
"Jetsons Meet the Flintstones, The ",
"Jetsons Movie, The ",
"Jetty, The ",
"Jimmy Neutron: Boy Genius",
"John Carter",
"Johnny Mnemonic",
"Joker",
"Jolley, Norman",
"Jones, Duncan",
"Jones, Terry",
"Journey Through the Black Sun ",
"Journey to Agartha ",
"Journey to the Beginning of Time, A",
"Journey to the Center of the Earth",
"Journey to the Center of Time",
"Journey to the Far Side of the Sun ",
"Journey to the Moon ",
"Journey to the Seventh Planet",
"Jubilee",
"Judge Dredd",
"Jules Verne's Rocket to the Moon",
"Jūnen",
"Jungle Boy ",
"Jungle Captive",
"Jungle Hell",
"Jungle, The",
"Jungle Woman",
"Junk Head",
"Jupiter Ascending",
"Jurassic Park",
"Jurassic Park III ",
"Just Imagine",
"Kadokawa Haruki",
"Kaiju Daisenso ",
"Kaiju Soshingeki ",
"Kaitei Gunkan ",
"Kamen Rider",
"Kamikaze",
"Kamikaze 1989",
"Karloff, Boris",
"Kate & Leopold",
"Kaufman, Charlie",
"Kaze no Tani no Nausicaä",
"Kdo Chce Zabít Jessii",
"Kelly, Richard",
"Kievnauchfilm",
"Kill or Be Killed ",
"Killdozer",
"Killer Ape",
"Killer Bats ",
"Killer Klowns from Outer Space",
"Killer Shrews, The",
"Killer with Wings ",
"Killers from Space",
"Kimball, Ward",
"King and the Mockingbird, The",
"King Dinosaur",
"King Kong",
"King Kong Tai Gojira ",
"King Kong vs. Godzilla ",
"King of Thorn",
"King Size ",
"Kingdom of the Spiders",
"Kingsajz",
"Kino's Journey",
"Kirara ",
"Kiss and Kill ",
"Kiss Me Deadly",
"Kiwerski, Krzysztof",
"Klaabu kosmoses",
"Knights of Sidonia",
"Knowing",
"Kolchak: The Night Stalker",
"Kon Satoshi",
"Konec Srpna V Hotelu Ozón",
"Konga",
"Kosmicheskiy Reys: Fantasticheskaya Novella",
"Krakatit ",
"Kronos",
"Kubrick, Stanley",
"Kumo no Mukō, Yakusoku no Basho ",
"La Antena ",
"Ladd, Fred",
"Lady and the Monster, The",
"Lady in the Water",
"Lair of the White Worm, The ",
"Land of the Dead",
"Land that Time Forgot, The",
"Lang, Fritz",
"Laputa: Castle in the Sky ",
"Laputa: The Flying Island ",
"Larson, Glen A",
"Laserblast",
"Last Airbender, The ",
"Last and First Men",
"Last Battle, The ",
"Last Chase, The",
"Last Days of Man on Earth, The ",
"Last Days on Mars, The ",
"Last Dinosaur, The",
"Last Jedi, The ",
"Last Man on Earth, The",
"Last Man on Earth, The [2] ",
"Last Mimzy, The",
"Last Night",
"Last Starfighter, The",
"Last Wave, The",
"Last Woman on Earth",
"Lathe of Heaven, The",
"Lawnmower Man, The",
"Lawrence, Ray ",
"League of Extraordinary Gentlemen, The",
"Leech ",
"Leech Woman, The",
"Legend of Hell House, The ",
"Lemony Snicket's A Series of Unfortunate Events ",
"Lenkov, Peter M",
"Lensman [film]",
"Leroy & Stitch ",
"Lesson, The",
"Lester, Richard",
"Let's Visit the World of the Future ",
"Leviathan",
"Life Returns",
"Lifeforce",
"Lifepod",
"Lift, De",
"Lilo & Stitch",
"Lilo & Stitch 2: Stitch Has a Glitch ",
"Lily C.A.T.",
"Limitless",
"Liquid Sky",
"Little Girl Who Conquered Time ",
"Little Nemo: Adventures in Slumberland ",
"Little Shop of Horrors, The ",
"Live Again, Die Again ",
"Living and Working in Space: The Countdown Has Begun",
"Livingston, Harold",
"Lobster, The",
"Lockout",
"Logan's Run",
"Looker",
"Looney Toons ",
"Looper",
"Lord of the Flies",
"Lords of the Deep ",
"Lost Atlantis ",
"Lost Continent",
"Lost Continent, The",
"Lost Horizon",
"Lost in Space",
"Lost Missile, The",
"Lost Planet Airmen",
"Lost Planet, The",
"Lost Thing, The",
"Lost World: Jurassic Park, The ",
"Lost World, The",
"Love",
"Love City ",
"Love War, The",
"Lucas, George",
"Lucy",
"Luna",
"Lynch, David",
"Lyndon, Barré ",
"Lyndon, Barry ",
"M.A.R.S. ",
"Mac and Me ",
"Machine, The",
"Maciste e la Regina di Samar",
"Macnee, Patrick",
"Macross ",
"Mad Ghoul, The",
"Mad Love ",
"Mad Max",
"Mad Max 2",
"Mad Max Beyond Thunderdome",
"Mad Max: Fury Road",
"Mad Monster, The",
"Made in Abyss: Dawn of the Deep Soul",
"Madhouse",
"Magic Christian, The ",
"Magnetic Monster, The",
"Mains d'Orlac, Les ",
"Maison en Petits Cubes, La",
"Maître du temps, Le",
"Making Mr Right",
"Malevil",
"Man and His Mate ",
"Man Beast",
"Man Called Flintstone, The",
"Man from Beyond, The",
"Man from Earth, The ",
"Man from Planet X, The",
"Man from U.N.C.L.E., The",
"Man Hunt ",
"Man in the Moon",
"Man in the Steel Mask, The ",
"Man in the White Suit, The",
"Man Made Monster",
"Man of Steel",
"Man They Could Not Hang, The",
"Man Who Fell to Earth, The",
"Man Who Haunted Himself, The ",
"Man Who Thought Life, The ",
"Man Who Turned to Stone, The",
"Man With Nine Lives, The",
"Man with the Power, The",
"Man with the X-Ray Eyes, The ",
"Man with Two Brains, The",
"Manchurian Candidate, The",
"Manden der Taenkte Ting",
"Mandrake the Magician",
"Man's Best Friend",
"Manster, The",
"Mantley, John",
"Manutara ",
"March of the Monsters, The ",
"Marine Express ",
"Maris the Choujo",
"Marjorie Prime",
"Mark of the Vampire ",
"Marker, Chris",
"Marooned",
"Mars Attacks!",
"Mars Invades Puerto Rico ",
"Mars-Mania ",
"Mars Needs Moms",
"Mars Needs Women",
"Martian Child, The ",
"Martian Successor Nadesico: The Motion Picture ",
"Martian, The [film]",
"Marvel Cinematic Universe",
"Mary Shelley's Frankenstein",
"Mask of Fu Manchu, The",
"Master of Terror ",
"Master of the World",
"Masters of the Universe",
"Matango",
"Matinee",
"Matrix Reloaded, The",
"Matrix Revolutions, The",
"Matrix, The",
"Max Headroom",
"Maximum Overdrive ",
"Maze, The",
"Mazinger Z ",
"Mechanical Man, The",
"Mechte Navstrechu",
"Medusa Touch, The",
"Meet the Applegates",
"Meet the Robinsons",
"Meeting, The",
"Megamind",
"Megaville",
"Meidän poikamme ilmassa – me maassa",
"Meitantei Holmes ",
"Mekagojira no Gyakushu ",
"Melancholia",
"Melchior, Ib",
"Méliès, Georges",
"Memento ",
"Memoirs of a Survivor",
"Memoirs of an Invisible Man",
"Memories",
"Men in Black",
"Men in Black 3 ",
"Men in Black II ",
"Men Must Fight",
"Men with Steel Faces ",
"Mephisto Waltz, The",
"Mergl, Václav",
"Merrie Melodies ",
"Mesa of Lost Women",
"Message from Mars, A",
"Message from Moonbase Alpha",
"Metalstorm: The Destruction of Jared-Syn",
"Meteor",
"Meteor Man, The",
"Meteor Monster ",
"Metropolis",
"Metropolis [2]",
"Meyer, Nicholas",
"Midnight in Paris",
"Midnight Sky, The",
"Midnight Special",
"Mighty Joe Young",
"Mighty Peking Man, The",
"Millennium",
"Miller, George",
"Million Eyes of Sumuru, The ",
"Mimic",
"Mind Game",
"Mind of Mr Soames, The",
"Mind Snatchers, The",
"Mindwarp: An Infinity of Terror ",
"Minority Report",
"Miracle in the Rain ",
"Miracle Mile",
"Mirror of Time, The",
"Mirrormask ",
"Missile Monsters ",
"Missile to the Moon",
"Mission Galactica: The Cylon Attack ",
"Mission Mars",
"Mission Stardust ",
"Mission to Mars",
"Mist, The",
"Mr Drake's Duck",
"Mr Hublot",
"Mr Joseph Young of Africa ",
"Mr. Nobody",
"Mistress of Atlantis, The ",
"Mitani Kōki",
"Mitchells vs the Machines, The",
"Miyazaki Hayao",
"Mobile Suit Gundam",
"Modest Heroes",
"Modesty Blaise ",
"Moebius [film]",
"Mole People, The",
"Monde Tremblera, Le ",
"Monitors, The",
"Monkey Business",
"Monkey Man, The ",
"Monkey Shines",
"Monolith Monsters, The",
"Mononoke Hime ",
"Monster ",
"Monster and the Girl, The",
"Monster from Green Hell",
"Monster from the Ocean Floor",
"Monster Maker ",
"Monster on the Campus",
"Monster on the Hill ",
"Monster that Challenged the World, The",
"Monster Zero ",
"Monsters [film]",
"Monsters from Mars ",
"Monsters from the Unknown Planet ",
"Monsters, Inc.",
"Monsters Invade Expo 70 ",
"Monsters University ",
"Monsters vs. Aliens",
"Monstrosity ",
"Monty Python's Flying Circus",
"Moon [film]",
"Moon 44 ",
"Moon Pilot",
"Moon, The ",
"Moon Zero Two",
"Moonraker",
"Moore, Ronald D",
"More Wild, Wild West ",
"Mōretsu Pirates",
"Morons from Outer Space",
"Mort en Direct, La",
"Mortal Kombat ",
"Morte Viene dal Pianeta Aytin, La",
"Morte Viene dallo Spazio, La",
"Most Dangerous Game, The",
"Most Dangerous Man Alive, The",
"Most Dangerous Man in the World, The",
"Mosura",
"Mosura Tai Gojira ",
"mother! [film]",
"Mothra ",
"Mouse on the Moon, The ",
"Mouse that Roared, The ",
"Murzilka na Sputnike",
"Mutant",
"Mutations",
"Mutiny in Outer Space",
"My Name is Modesty ",
"My Neighbor Totoro ",
"My Science Project",
"My Stepmother is An Alien",
"Mysterians, The ",
"Mysterious Invader ",
"Mysterious Island",
"Mystery of the Ghoul ",
"Mystery of the Third Planet",
"Na Srebrnym Globie ",
"Nackte und der Satan, Die ",
"Nadesico Prince of Darkness ",
"Naked Jungle, The",
"Naked Lunch ",
"Nankai no Daiketto ",
"Natali, Vincenzo",
"Nausicaä of the Valley of the Wind ",
"Návštěva z Vesmíru",
"Nazis at the Center of the Earth ",
"Neanderthal Man, The",
"Near Dark",
"Nebo Zovyot",
"Nemesis",
"Neo Tokyo",
"Neptune Factor, The",
"Never Let Me Go",
"Neverending Story, The ",
"New Barbarians, The ",
"New Rose Hotel ",
"Next",
"Niccol, Andrew",
"Night Caller, The",
"Night Fright",
"Night of the Big Heat",
"Night of the Blood Beast",
"Night of the Carrots, The",
"Night of the Comet",
"Night of the Lepus",
"Night of the Living Dead",
"Night of the Silicates ",
"Night on the Galactic Railroad",
"Night Shadows ",
"Night Slaves",
"Night Stalker, The ",
"Night Strangler, The",
"Night that Panicked America, The",
"Night the World Exploded, The",
"Night without Stars ",
"Nightflyers ",
"Nightwing ",
"Nines, The",
"Nineteen Eighty-Four",
"Nippon Chinbotsu",
"Nippon Igai Zenbu Chinbotsu ",
"No Blade of Grass",
"No Escape",
"No Highway in the Sky ",
"Noah",
"Noiseman Soundinsect",
"Nolan, Christopher",
"Nope",
"North to Freedom ",
"Not of This Earth",
"Nuclear Countdown ",
"Nude on the Moon",
"Nuovi Barbari, I ",
"Nutty Professor, The",
"Ō-Atari Sora no Entaku",
"Oblivion",
"Oboler, Arch",
"O'Brien, Willis H",
"Octaman",
"October Sky ",
"Offret ",
"Old Legends Never Die ",
"Omega Man, The",
"On the Beach",
"On the Silver Globe ",
"On to Mars ",
"Once in a New Moon ",
"Once Upon a Time",
"One Hour to Doomsday ",
"One Million B.C.",
"One Million Years B.C.",
"Oneamisu no Tsubasa",
"Only Lovers Left Alive",
"Open your Eyes ",
"Operation Ganymed",
"Operation Monsterland ",
"Or, L' ",
"Órbita Mortal ",
"Orlacs Hände",
"Orme, Le ",
"Oru Kaiju Daishingeki ",
"Oshii Mamoru",
"Oswald the Lucky Rabbit",
"Ōtomo Katsuhiro",
"Out of the Darkness ",
"Outer Space Jitters",
"Outland",
"Outlander",
"Outlanders",
"Pacific Rim",
"Padua, Sydney",
"Pal, George",
"Palin, Michael ",
"Palm Springs",
"Pandorum",
"Panic in Year Zero!",
"Panic on the Trans-Siberian Express ",
"Panico en el Transiberiano",
"Pan's Labyrinth",
"Paprika",
"Parallax View, The ",
"Parasite Murders, The",
"Paris 2054: Renaissance ",
"Paris qui Dort",
"Pärn, Priit",
"Parts: The Clonus Horror",
"Patrick",
"Paul",
"Paycheck",
"Peace Game, The ",
"Penal Colony ",
"People that Time Forgot, The",
"People, The",
"People Who Own the Dark, The",
"Per Aspera ad Astra ",
"Percy ",
"Percy's Progress ",
"Pereval",
"Perfect Woman, The",
"Perils from the Planet Mongo ",
"Perry Rhodan – SOS aus dem Weltall ",
"Phantasm",
"Phantasm II ",
"Phantom Empire, The",
"Phantom from 10,000 Leagues, The",
"Phantom from Space",
"Phantom Menace, The ",
"Phantom Planet, The",
"Phantom, The",
"Phase IV",
"Philadelphia Experiment, The",
"Phoenix 2772",
"Phoenix: Space Chapter, The",
"Pi",
"Pianeta degli Uomini Spenti, Il",
"Pianeta Errante, Il",
"Picture Book 1936 ",
"Picture of Dorian Gray, The ",
"Pier, The ",
"Pierce, Jack P",
"Pink Panther Strikes Again, The",
"Piranha",
"Piranha II ",
"Pirates of 1920, The",
"Pirates of the Caribbean: On Stranger Tides ",
"Pitch Black",
"Place Promised in Our Early Days, The ",
"Plan 9 from Outer Space",
"Planet 51",
"Planet Busters ",
"Planet Earth",
"Planet Men ",
"Planet of Blood ",
"Planet of Dinosaurs",
"Planet of Horrors ",
"Planet of Storms ",
"Planet of the Apes",
"Planet of the Dead ",
"Planet of the Female Invaders ",
"Planet of the Lifeless Men ",
"Planet of the Vampires ",
"Planet Outlaws ",
"Planet Terror",
"Planeta Bur",
"Planeta de las Mujeres Invasoras, El",
"Planetarian: Storyteller of the Stars ",
"Planetary Giants ",
"Planète Sauvage, La",
"Plutonium ",
"Poitier, Sidney",
"Polygon",
"Ponyo on the Cliff by the Sea",
"Port Sinister",
"Postman, The",
"Power, The",
"Predator",
"Predator 2",
"Predators",
"Prehistoric Valley ",
"Prehistoric Women",
"Prehistoric World ",
"President Vanishes, The",
"President's Analyst, The",
"Prestige, The",
"Pride of Palomar, The ",
"Priest",
"Primal Impulse ",
"Primal Scream",
"Primer",
"Prince of Darkness",
"Prince of Space",
"Princes and Princesses",
"Princess Mononoke",
"Prípad pro zacínajícího kata ",
"Prison Colony, The ",
"Private Life of Sherlock Holmes, The",
"Privilege",
"Prix du Danger, Le",
"Prize of Peril, The ",
"Probe ",
"Project A-ko",
"Project Genocide ",
"Project Moonbase",
"Project V.I.P.E.R.",
"Project X",
"Projected Man, The",
"Promare",
"Prometheus",
"Prophecy",
"Prospero's Books ",
"Proteus ",
"Proyas, Alex",
"Psycho-Pass",
"Punishment Park",
"Puppet Masters, The",
"Purple Death from Outer Space ",
"Purple Monster Strikes, The",
"Pursuit",
"Push",
"Python, Monty ",
"Q",
"Q: The Winged Serpent ",
"Quatermass",
"Quatermass and the Pit",
"Quatermass Conclusion, The ",
"Quatermass II",
"Quatermass Xperiment, The",
"Queen of Blood",
"Queen of Outer Space",
"Quest for Fire",
"Quest for Love",
"Questor Tapes, The",
"Quiet Earth, The",
"Quiet Killer ",
"Quintet",
"Rabid",
"Race to Witch Mountain",
"Radar Men from the Moon",
"Radio-Mania ",
"Radio Ranch ",
"Radon",
"Raffill, Stewart ",
"Rage: Carrie 2, The",
"Raiders from the Moon ",
"Raiders of the Lost Ark ",
"Raise the Titanic! ",
"Raptor ",
"Rascal Does Not Dream of Bunny Girl Senpai",
"Rat Saviour, The ",
"Raumschiff Venus Antwortet Nicht ",
"Raw Meat ",
"Ray Gun Terror, The ",
"Rayon Invisible, Le ",
"Re-Animator",
"Re-Animator II ",
"Real Genius",
"Real Steel",
"Red Dawn",
"Red Planet",
"Red Planet Mars",
"Redline",
"Regular Show",
"Rehla ilal Kamar",
"Reign of Fire",
"Relativity [film] ",
"Relic, The",
"Reluctant Astronaut, The",
"Renaissance",
"Replicant",
"Repo Man",
"Repo Men",
"Reptilicus",
"Resident Evil [film]",
"Resident Evil: Afterlife",
"Resident Evil: Apocalypse",
"Resident Evil: Extinction ",
"Resurrection of Clayton Zachary Wheeler, The ",
"Resurrection of Zachary Wheeler, The",
"Return from Witch Mountain ",
"Return of Captain America ",
"Return of Captain Invincible, The",
"Return of Doctor X, The ",
"Return of Godzilla, The ",
"Return of Sherlock Holmes, The",
"Return of Swamp Thing, The ",
"Return of the Fly",
"Return of the Giant Monsters, The ",
"Return of the Incredible Hulk ",
"Return of the Jedi ",
"Return, The",
"Revenge of Frankenstein, The ",
"Revenge of the Creature",
"Revenge of the Gods ",
"Revenge of the Mysterons from Mars ",
"Revenge of the Sith ",
"Revenge of the Stepford Wives ",
"Revengers Tragedy ",
"Re:Zero – Starting Life in Another World",
"Riddick",
"Riders to the Stars",
"Ring",
"Rio 70",
"Rise of the Planet of the Apes",
"Rise of the Silver Surfer ",
"Road, The",
"Road to Hong Kong, The",
"Road to the Stars ",
"Road Warrior, The ",
"Robinson Crusoe on Mars",
"RoboCop",
"RoboCop 2",
"RoboCop 3",
"Roboforce ",
"Robot Carnival",
"Robot Jox",
"Robot Monster",
"Robot vs. the Aztec Mummy, The",
"Robots [film]",
"Rocket Attack U.S.A.",
"Rocket Man, The",
"Rocket to the Moon ",
"Rocketeer, The",
"Rocketship X-M",
"Rockin' with Judy Jetson ",
"Rocky Horror Picture Show, The",
"Rodan ",
"Roddenberry, Gene",
"Rodriguez, Robert",
"Roeg, Nicolas",
"Roger Corman's Frankenstein Unbound ",
"Rogue One: A Star Wars Story",
"Rōjin Z",
"Rollerball",
"Rollover",
"Romanek, Mark",
"Romero, George A",
"Rosemary's Baby",
"Rosencrantz and Guildenstern are Dead ",
"Roujin Z ",
"Runaway",
"Running Man, The",
"Russell, Ken",
"Russell, Ray",
"S1m0ne",
"Sacrifice, The ",
"Sahakyants, Robert",
"Sailor Moon",
"Sakaguchi Hironobu",
"Santa Claus Conquers the Martians",
"Santa Claus Defeats the Aliens ",
"Santo the Silver Mask vs The Martian Invasion",
"Sap Nin",
"Saraba Uchū Senkan Yamato: Ai no Senshitachi ",
"Saragossa Manuscript, The ",
"Satan Bug, The ",
"Satan's Satellites ",
"Satan's Triangle ",
"Satellite in the Sky",
"Satellite of Blood ",
"Saturn 3",
"Savages",
"Sayles, John",
"Sayonara Jupiter ",
"Scanner Cop ",
"Scanner Darkly, A",
"Scanner Force ",
"Scanners",
"Scanners II: The New Order ",
"Scanners III: The Takeover ",
"Scanners: The Showdown ",
"Schlangenei, Das ",
"Schlock",
"Schneer, Charles H ",
"School-Live!",
"Schweigende Stern, Der",
"Scorcher",
"Scotland Yard jagt Dr Mabuse",
"Scott Pilgrim vs. the World",
"Scott, Ridley",
"Scream and Scream Again",
"Screamers",
"Secombe, Andy",
"Seconds",
"Secret Kingdom, The ",
"Secret of Blue Water, The ",
"Secret of NIMH, The",
"Secret of the Loch, The",
"Secret of the Telegian",
"Secrets of F.P.1 ",
"Seddok ",
"Seddok, l'erede, di Satana ",
"Seksmisja",
"Seltzer, David",
"Sender, The",
"Sengoku Jieitai",
"Serenity",
"Sergeant Dead Head",
"Serial Films",
"Serpent's Egg, The",
"Seven Days in May ",
"Seven Faces of Dr Lao, The ",
"Sex Mission ",
"Shadow Men, The",
"Shadow on the Land",
"Shadow Returns, The ",
"Shadow Strikes, The ",
"Shadow, The",
"Shanhu Dao Shang de Siguang ",
"Shaun of the Dead ",
"She Creature, The",
"She Demons",
"She Devil",
"She Monster of the Night ",
"Sheena ",
"Sheena, Queen of the Jungle",
"Shi Nian Taiwan",
"Shinseiki Evangelion",
"Ship of Monsters",
"Ship to Heaven, A ",
"Shivers ",
"Short Circuit",
"Short Circuit 2 ",
"Shuto Shōshitsu ",
"Shuttered Room, The",
"Shyamalan, M Night",
"Siegel, Richard",
"Sight, The ",
"Signs",
"Silent Möbius",
"Silent Möbius 2",
"Silent Running",
"Silent Star, The ",
"Silent Village, The",
"Sinking of Japan, The ",
"Siodmak, Curt",
"Six Inches Tall ",
"Six Million Dollar Man, The",
"Sixth Sense, The ",
"Skullduggery",
"Sky Blue",
"Sky Calls, The ",
"Sky Captain and the World of Tomorrow",
"Sky Crawlers",
"Skyline",
"Slaughterhouse-Five",
"Slave Girls ",
"Sleeper",
"Sleeping Dogs ",
"Slipstream",
"Small Soldiers ",
"Smilla's Sense of Snow ",
"Smith, Dick",
"Smith, George Albert",
"Smith, Robert ",
"Snow Creature, The",
"Snow Devils, The ",
"Snowpiercer",
"Society",
"Solaris",
"Soldier",
"Something in the Dirt",
"Somewhere in Time",
"Son of Blob ",
"Son of Dr Jekyll, The",
"Son of Flubber",
"Son of Frankenstein ",
"Son of Godzilla ",
"Son of Kong",
"Sonidode de la Muerte, El ",
"Sorcerers, The",
"Sound of Horror, The",
"Sound of My Voice",
"Sound of Thunder, A",
"Source Code",
"Southern, Terry",
"Southland Tales",
"Soylent Green",
"Space Battleship Yamato ",
"Space Camp",
"Space Children, The",
"Space Cowboys",
"Space Devils ",
"Space Documentaries",
"Space Is the Place",
"Space Island ",
"Space Master X-7",
"Space Men",
"Space Monster ",
"Space Probe Taurus",
"Space Raiders ",
"Space Ship Sappy",
"Space Ship, The ",
"Space Sweepers",
"Space Truckers",
"Space Voyage, The ",
"Spaced Invaders",
"Spacehunter: Adventures in the Forbidden Zone",
"Spaceship to the Unknown ",
"Spaceship Venus Does Not Reply ",
"Spacesuit Films",
"Spaceways",
"Spaceways [fanzine] ",
"Special Bulletin",
"Species",
"Species II",
"Sphere",
"Spider-Man",
"Spider-Man 2",
"Spider-Man 3",
"Spider-Man: Far from Home",
"Spider, The [film] ",
"Spielberg, Steven",
"Splice",
"Split Second",
"Spook Who Sat by the Door, The ",
"Spooks!",
"Spriggan",
"Sputnik",
"Squirm ",
"Ssssnake ",
"Ssssssss!",
"Stadt ohne Juden, Die",
"Stalker",
"Star Man Films ",
"Star Pilot ",
"Star Trek [film]",
"Star Trek: First Contact",
"Star Trek: Generations",
"Star Trek II: The Wrath of Khan",
"Star Trek III: The Search for Spock",
"Star Trek: Insurrection",
"Star Trek Into Darkness",
"Star Trek IV: The Voyage Home",
"Star Trek: Nemesis",
"Star Trek: The Motion Picture",
"Star Trek V: The Final Frontier",
"Star Trek VI: The Undiscovered Country",
"Star Wars",
"Star Wars [franchise]",
"Star Wars: Episode I – The Phantom Menace",
"Star Wars: Episode II – Attack of the Clones",
"Star Wars: Episode III – Revenge of the Sith",
"Star Wars: Episode IV – A New Hope ",
"Star Wars: Episode V – The Empire Strikes Back",
"Star Wars: Episode VI – Return of the Jedi",
"Star Wars: Episode VII – The Force Awakens",
"Star Wars: Episode VIII – The Last Jedi",
"Starchaser: The Legend of Orin",
"Starcrash",
"Starevich, Ladislas ",
"Starewicz, Władysław",
"Stargate",
"Stargate: Continuum ",
"Stargate: Infinity ",
"Stargate: The Ark of Truth ",
"Starman",
"Starship Invasions",
"Starship Troopers",
"Starship Troopers 2: Hero of the Federation ",
"Starship Troopers 3: Marauder ",
"Starvengers ",
"Steamboy",
"Stepford Children, The ",
"Stepford Wives, The",
"Stephen King's the Lawnmower Man ",
"Stereo (Tile 3B of a CAEE Educational Mosaic)",
"Steven Spielberg Presents Pinky, Elmyra & The Brain ",
"Steven Universe: The Movie",
"Stingray",
"Stitch! The Movie ",
"Stolen Airship, The",
"Stone Age Romeos ",
"Stoppard, Tom",
"Storm Planet ",
"Storm Watch",
"Story of Mankind, The ",
"Stow, Percy",
"Stowaway",
"Stowaway to the Moon ",
"Straczynski, J Michael",
"Stranded in Space ",
"Strange Behavior ",
"Strange Days",
"Strange Invaders",
"Strange New World",
"Strange World of Planet X, The",
"Stranger from Venus",
"Stranger, The",
"Stranger Within, The",
"Strause, Colin ",
"Strause, Greg",
"Strick, Philip",
"Stryker ",
"Studio Gainax ",
"Studio Ghibli ",
"Studio Trigger ",
"Stuff, The",
"Submersion of Japan, The ",
"Suburban Commando",
"Suicide Squad",
"Sum of All Fears, The ",
"Summer Wars",
"Sumuru ",
"Sun Demon, The ",
"Sunn Classic Pictures",
"Sunshine",
"Super 8",
"Super Dimensional Fortress Macross",
"Super Inframan, The",
"Super Mario Bros.",
"Super Sentai",
"Supergirl",
"Superman [character]",
"Superman [film]",
"Superman and Scotland Yard ",
"Superman and the Jungle Devils ",
"Superman and the Mole Men ",
"Superman and the Strange People ",
"Superman Flies Again ",
"Superman II",
"Superman III",
"Superman in Exile ",
"Superman IV: The Quest for Peace",
"Superman Returns",
"Superman's Peril ",
"SuperMarionation",
"Supersonic Saucer",
"Sur un air de Charleston",
"Surrogates",
"Suspiria",
"Swamp Thing",
"Swamp Thing II ",
"Swarm, The ",
"Synchronic",
"Synecdoche, New York",
"Taekoesu Yonggary",
"Tales of Frankenstein",
"Tales of Hoffmann, The ",
"Tamala 2010: A Punk Cat in Space",
"Tank Girl: The Movie",
"Tarantula",
"Tarasov, Vladimir",
"Target Earth!",
"Tarkovsky, Andrei",
"Tarzan",
"Tarzan Films",
"Tarzan of the Apes ",
"Tarzan the Ape Man ",
"Tausend Augen des Dr Mabuse, Die",
"Teenage Caveman ",
"Teenage Monster",
"Teenage Mutant Ninja Turtles",
"Teenage Mutant Ninja Turtles II: The Secret of the Ooze ",
"Teenage Mutant Ninja Turtles III ",
"Teenagers from Outer Space",
"Temné Slunce",
"Tempbot ",
"Ten Years Thailand",
"Tenet",
"Tenkū no shiro Laputa",
"Tenth Victim, The ",
"Terminal Man, The",
"Terminator 2: Judgment Day",
"Terminator 3: Rise of the Machines",
"Terminator Genisys",
"Terminator, The",
"Terror from the Sun ",
"Terror from the Year 5000 ",
"Terror in the Night ",
"Terror is a Man",
"Terror of Mechagodzilla ",
"Terror Strikes, The ",
"Terrore Nello Spazio",
"Terrornauts, The",
"Terrorvision",
"Testament",
"Testament des Dr Mabuse, Das",
"Tetra Vaal ",
"Tetsujin 28 Go",
"Tetsuo",
"Tetsuo II: Bodyhammer",
"Tetsuo: The Iron Man ",
"Them!",
"There Will Come Soft Rains ",
"These Are the Damned ",
"They ",
"They Came from Beyond Space",
"They Came from Within ",
"They Live",
"They Saved Hitler's Brain ",
"They Were Eleven",
"Thing from Another World, The ",
"Thing, The",
"Thing with Two Heads, The ",
"Things to Come",
"Thirteenth Floor, The",
"Thirty Foot Bride of Candy Rock, The",
"This Is Not a Test",
"This Island Earth",
"Thom, Robert",
"Thor",
"Thor: Ragnarok",
"Thor: the Dark World",
"Those Fantastic Flying Fools ",
"Thousand Eyes of Dr Mabuse, The ",
"Threads",
"Three Stooges Films",
"Three Stooges in Orbit, The",
"Three Stooges Meet Hercules, The",
"Three Worlds of Gulliver, The ",
"Thunderball ",
"Thunderbird Six ",
"Thunderbirds",
"Thunderbirds Are Go ",
"THX 1138",
"Tidal Wave ",
"Tiger & Bunny",
"Time After Time",
"Time Bandits",
"Time Killer, The ",
"Time Machine, The",
"Time Masters",
"Time of Roses, A",
"Time Slip ",
"Time Trackers ",
"Time Travelers",
"Time Travelers, The",
"Time Traveler's Wife, The",
"Time Warp ",
"Timecop",
"Timecrimes ",
"Timeline",
"Timerider: The Adventures of Lyle Swann",
"Timescape ",
"Timeslip [film]",
"Timestalkers",
"Tobor the Great",
"Toki o Kakeru Shōjo",
"Tolkin, Michael",
"Tomerlin, John",
"Tomino Yoshiyuki",
"Tomorrow Calling ",
"Tomorrow I'll Wake Up and Scald Myself with Tea ",
"Tomorrow, When the War Began",
"Tonari no Totoro",
"Toomorrow",
"Top o Nerae",
"Total Recall",
"Toter Sucht Seiner Mörder, Ein ",
"Totò in the Moon ",
"Totò nella Luna",
"Towering Inferno, The ",
"Toxic Avenger Part II ",
"Toxic Avenger, The",
"Toy Box Series Episode 3: Picture Book 1936",
"Track of the Moon Beast",
"Trancers",
"Trans-Atlantic Tunnel ",
"Transcendence [film]",
"Transfer",
"Transformers",
"Transformers: Age of Extinction",
"Transformers: Dark of the Moon",
"Transformers: Revenge of the Fallen",
"Transformers  The Movie, The",
"Tranzor Z ",
"Trapped in Space",
"Treasure Planet",
"Tremors",
"Trial of the Incredible Hulk ",
"Triangle",
"Triangle, The ",
"Trigger",
"Trigun",
"Trip to Jupiter, A ",
"Trip to Mars, A ",
"Trip to the Moon, A ",
"Trnka, Jiří ",
"Trog",
"Trollenberg Terror, The",
"Tron",
"Tron: Legacy",
"Trudno byt' bogom",
"Truman Show, The",
"Trumbull, Douglas",
"Tsuburaya Eiji",
"Tumannost' Andromedy",
"Tunnel, Der",
"Tunnel, The",
"Twelve Monkeys",
"Twilight Zone: The Movie ",
"Twilight's Last Gleaming",
"Two Faces of Dr Jekyll, The",
"Two Lost Worlds",
"Two Worlds of Charlie Gordon, The ",
"Twohy, David",
"Twonky, The",
"Uchida Tomu ",
"Uchū Daisensō",
"Uchū no Senshi ",
"Uchū Senkan Yamato",
"Uchūdaikaijū Girara",
"UFO Incident, The",
"Ultimate Warrior, The",
"Ultimo Uomo della Terra, L'",
"Ultraman",
"Unbreakable",
"Undead, The",
"Under the Skin",
"Undersea Super Train: Marine Express",
"Underwater City, The",
"Undying Monster, The",
"Unearthly Stranger",
"Unearthly, The",
"Unholy Love ",
"United States: It Can't Happen Here ",
"Universal Soldier",
"Unknown Island",
"Unknown Terror, The",
"Unknown World",
"Untamed Women",
"Until the End of the World",
"Up",
"Upstream Color",
"Urusei Yatsura",
"Urusei Yatsura 2: Beautiful Dreamer",
"Usual Suspects, The",
"V for Vendetta",
"Valerian and the City of a Thousand Planets",
"Valley of Eagles",
"Valley of Gwangi, The",
"Valley of the Dragons",
"Valley of the Eagles ",
"Valley of the Mists ",
"Vampire Bat, The",
"Vampire Beast Craves Blood, The ",
"Vampire, The",
"Vampirella",
"Van Ronkel, Rip",
"Vanilla Sky",
"Varan the Unbelievable",
"Vel'd",
"Veldt, The ",
"Velle, Gaston",
"Vengeance",
"Vengeance of Fu Manchu, The ",
"Venus Wars",
"Venusian, The ",
"Verhoeven, Paul",
"Videodrome",
"Village of the Damned",
"Village of the Giants ",
"Village, The",
"Villeneuve, Denis",
"Virtual Storm ",
"Virtuosity",
"Virus",
"Vivarium",
"Voices of a Distant Star ",
"von Harbou, Thea",
"Vortex [film] ",
"Voyage à Travers l'Impossible, Le",
"Voyage dans la Lune, Le",
"Voyage de Gulliver à Lilliput et chez les géants, Le ",
"Voyage into Space ",
"Voyage sur Jupiter, Le",
"Voyage to the Bottom of the Sea",
"Voyage to the End of the Universe ",
"Voyage to the Planet of Prehistoric Women ",
"Voyage to the Prehistoric Planet ",
"Vulture, The",
"VVitch: A New-England Folktale, The",
"Vynález Zkázy",
"Wachowski, Andy ",
"Wachowski, Lana",
"Wachowski, Larry ",
"Wachowski, Lilly ",
"Wakko's Wish ",
"Walking Dead, The",
"WALL-E",
"Walt Disney Company, The",
"Wandering Earth, The",
"War Between the Planets ",
"War Game, The",
"War-Gods of the Deep",
"War of 1995, The ",
"War of the Colossal Beast ",
"War of the Monsters ",
"War of the Planets, The ",
"War of the Satellites",
"War of the Worlds",
"War of the Worlds  Next Century, The ",
"WarGames",
"Warlock ",
"Warlords of Atlantis ",
"Warner Bros. Cartoons",
"Warning from Space",
"Warriors of the Wasteland ",
"Warriors of the Wind ",
"Wasei King Kong",
"Wasp Woman, The",
"Watchmen",
"Watermelon Man ",
"Waterworld",
"Watkins, Peter",
"Way ... Way Out",
"Weapons of Destruction ",
"Weekend",
"Weird Science",
"Weitz, Chris",
"Welcome to Blood City",
"Welcome to Oblivion ",
"Welles, Orson",
"Wells, Simon",
"Welt Am Draht",
"Went the Day Well?",
"Werewolf, The",
"Westworld",
"Whale, James",
"What's So Bad about Feeling Good?",
"Whedon, Joss",
"When Dinosaurs Ruled the Earth",
"When the Wind Blows",
"When Time Ran Out ... ",
"When Worlds Collide",
"Where Have All the People Gone?",
"Where the Lighthouse Shines across the Bay ",
"Whip Hand, The",
"Whirling the Worlds ",
"Whisperer in Darkness, The ",
"White, Jon Manchip",
"Who?",
"Who Framed Roger Rabbit",
"Who Is Julia?",
"Who Would Kill Jessie? ",
"Who's Out There ",
"Wicked City",
"Wild in the Streets",
"Wild, Wild Planet, The ",
"Wild, Wild West Revisited, The ",
"Wild, Wild West, The",
"Wilder, Myles",
"Wilder, W Lee",
"Willard ",
"Willie Wonka and the Chocolate Factory ",
"Wind",
"Wind Named Amnesia, A",
"Winged Serpent, The ",
"Winston, Stan ",
"Wise, Robert",
"Wishing Machine, The ",
"Witch, The ",
"Without Warning",
"Without Warning [2]",
"Wizard of Mars, The",
"Wizard, The ",
"Wojna Światów  Następne Stulecie ",
"Wolf House, The",
"Wolf's Call, The",
"Wolverine, The ",
"Woman Eater, The",
"Woman in the Moon, The ",
"Womaneater ",
"Womb",
"Wonderful Days ",
"Wonderful Galaxy of Oz, The",
"Wood, Edward D, Jr",
"Woodring, Jim",
"Woolverton, Linda",
"World of Space, The ",
"World of the Talisman, The ",
"World of Tomorrow",
"World on a Wire ",
"World, the Flesh and the Devil, The",
"World War III 41 Hours of Fear ",
"World War III Breaks Out",
"World War Z",
"World Will Shake, The",
"World Without End",
"Wreck-It Ralph",
"X-Files: Fight the Future, The ",
"X-Files: I Want to Believe, The ",
"X from Outer Space, The ",
"X-Men ",
"X-Men 2 ",
"X-Men 2: X-Men United ",
"X-Men Films",
"X-Men: First Class ",
"X-Men Origins: Wolverine ",
"X-Men: The Last Stand ",
"X  The Man with the X-Ray Eyes",
"X the Unknown",
"X2 ",
"X2: X-Men United ",
"Xtro",
"Yesterday Machine, The",
"Yeux sans Visage, Les",
"Yokai Monsters: 100 Monsters",
"Yokai Monsters: Spook Warfare",
"Yongary, Monster from the Deep ",
"Yosei Gorasu",
"You Only Live Twice",
"Young Einstein",
"Young Frankenstein ",
"Young Sherlock Holmes ",
"Youth Without Youth ",
"Yuasa Masaaki",
"Z.P.G.",
"Zardoz",
"Zathura: A Space Adventure",
"Zecca, Ferdinand",
"Zeiram",
"Zeiram 2 ",
"Zemeckis, Robert",
"Zeram ",
"Zero Population Growth ",
"Zero Theorem, The",
"Zítra Vstanu a Opařím Se Čajem",
"Zombie ",
"Zombies [film] ",
"Zombies of the Stratosphere",
"Zone Troopers",
"Zotz!",]