tv_list = [
"3rd Rock from the Sun",
"7 Days ",
"86",
"1899",
"1984",
"1990",
"A.D. Police Files ",
"A.D. Police: To Protect and Serve ",
"A for Andromeda",
"Abrahams, Mort",
"ACCA",
"Accel World",
"AD Police Files",
"Adam Adamant Lives!",
"Adventure Time",
"Adventures of Batman and Robin, The",
"Adventures of Brisco County, Jr, The",
"Adventures of Dr Fu Manchu, The",
"Adventures of Jonny Quest, The ",
"Adventures of Superman, The ",
"Adventures of Twizzle, The ",
"Adventures of Wonder Woman, The ",
"Æon Flux",
"Agent Elvis",
"Akudama Drive",
"Akuma-kun",
"Alex Mack ",
"ALF",
"Alfred Hitchcock Hour, The ",
"Alfred Hitchcock Presents",
"Alias",
"Alice in Borderland",
"Alien Nation",
"Alien News Desk",
"Alien Nine",
"All-New Super Friends Hour, The",
"Allen, Irwin",
"Altered Carbon ",
"Alternative 3",
"Amazing 3, The ",
"Amazing Spider-Man, The",
"Amazing Stories [tv]",
"Amazing World of Gumball, The",
"American Inferno ",
"Amerika",
"Amphibia",
"Anderson, Gerry",
"Anderson, Sylvia ",
"Andromeda",
"Andromeda Breakthrough, The",
"Angel Links ",
"Animaniacs",
"Another Flip for Dominick ",
"Apparitions",
"Arcane",
"Archer",
"Archer's Goon ",
"Ark II",
"Armitage III",
"Ascendance of a Bookworm",
"Asteroid [tv]",
"Astra Lost in Space",
"Astro Boy",
"Astroboy ",
"Atom Squad",
"Atomic Betty",
"Attack on Titan",
"Automan",
"Automaton in Long Sleep, An ",
"Avatar: The Last Airbender",
"Avengers, The",
"Babylon 5",
"Baoh",
"Barton, Dick ",
"Batman [tv]",
"Batman and the Super 7 ",
"Batman/Superman Hour, The ",
"Batman/Tarzan Adventure Hour, The",
"Batman: The Animated Series ",
"Batman: The Brave and the Bold",
"Battle Angel",
"Battle of the Planets",
"Battlestar Galactica",
"Baymax ",
"BBC Radiophonic Workshop, The",
"Beastars",
"Beauty and the Beast",
"Behind the Planet of the Apes",
"Bennett, Harve",
"Bewitched ",
"Beyond Westworld",
"Big Hero 6",
"Big Mouth",
"Big O",
"Big Pull, The",
"Bigfoot and Wildboy",
"Bionic Woman, The",
"Birdman and the Galaxy Trio",
"Birds of Prey",
"Black Archive, The ",
"Black Magic M-66",
"Black Mirror",
"Black Scorpion",
"Blake's Seven",
"Blaue Palais, Das",
"Blue Submarine No. 6",
"Blue Thunder",
"BNA: Brand New Animal",
"Bodacious Space Pirates ",
"BoJack Horseman",
"Boogiepop and Others",
"Boogiepop Phantom",
"Boucher, Chris",
"Bravest Warriors",
"BraveStarr ",
"Brennert, Alan",
"Bride of the Incredible Hulk ",
"Briggs, Andy",
"Bubblegum Crash ",
"Bubblegum Crisis",
"Bubblegum Crisis Tokyo 2040 ",
"Bubuki Buranki",
"Buck Rogers ",
"Buck Rogers in the 25th Century",
"Burning Zone, The",
"Byoreseo on Geudae",
"Camp Camp",
"Caprica",
"Captain Midnight",
"Captain Nice",
"Captain Power and the Soldiers of the Future",
"Captain Scarlet and the Mysterons",
"Captain Star ",
"Captain Video",
"Captain Z-Ro",
"Carmen Sandiego",
"Casshan",
"Cassutt, Michael",
"Cells at Work!",
"Cells at Work! Code Black",
"Centaurworld",
"Chainsaw Man",
"Challenge of the Superheroes ",
"Champions, The",
"Changes, The",
"Chapman, Graham ",
"Chicken from Outer Space, The ",
"Chobits",
"Chronicle, The ",
"Chuck",
"City Beneath the Sea",
"City of Ghosts",
"Clangers, The",
"Clear Horizon, The",
"Cleese, John ",
"Cleopatra 2525",
"Cleopatra in Space",
"Cliffhangers ",
"Cliffhangers: Stop Susan Williams ",
"Clone High",
"Cloning of Joanna May, The",
"Close Enough",
"Cohen, Larry",
"Cold Lazarus ",
"Commando Cody ",
"Commando Cody: Sky Marshal of the Universe",
"Community",
"Concrete Revolutio",
"Conquest of the Earth ",
"Conway, Gerard F",
"Cooper, Richard",
"Corbett, Tom ",
"Cosmic Monster, The ",
"Cosmos [tv] ",
"Cotton, Donald",
"Counterpart",
"Courage the Cowardly Dog",
"Cowboy Bebop",
"Craig of the Creek",
"Creature, The ",
"Crusade",
"Cuphead Show!, The",
"Curry, Graeme",
"CyberCity Oedo 808",
"Cyberpunk: Edgerunners",
"Cybersix",
"Cyborg 009",
"Dai-Guard",
"Daleks: Invasion Earth 2150 A.D.",
"Dallos",
"Danger and Eggs",
"Dante, Joe",
"Daredevil",
"Dark",
"Dark Angel",
"Dark Shadows",
"Dark Skies ",
"Darkwing Duck",
"Davison, Peter",
"Day After Tomorrow, The [tv]",
"Day of the Triffids, The",
"DC Super Hero Girls",
"Dead End: Paranormal Park",
"Dead Hand",
"Deadly Games",
"Deca-Dence",
"Deep Space Nine ",
"Defenders of the Earth",
"Defenders, The",
"Defying Gravity",
"Delta Space Mission",
"Destination Saturn ",
"Devilman Crybaby",
"Dexter's Laboratory",
"Dino Boy in the Lost Valley ",
"Dinosaurs [tv]",
"Dirty Pair",
"Disenchantment",
"Disney on Television",
"Disney, Walt ",
"Dr. Horrible's Sing-Along Blog",
"Dr Shrinker",
"Dr Stone",
"Doctor Who",
"Dr Who and the Daleks",
"Dogs in Space",
"Dollhouse",
"Dominion Tank Police",
"Donner, Richard",
"Don't Hug Me I'm Scared",
"Doomwatch",
"Dorohedoro",
"Dragon Ball",
"Dragon Ball Z",
"Dream Hunter REM",
"Duckman",
"DuckTales",
"Early Edition",
"Earth 2 ",
"Earth: Final Conflict",
"Earthworm Jim",
"Eden",
"Eden of the East",
"Edge of Darkness",
"Eerie, Indiana",
"El Hazard The Magnificent World",
"Electra Woman and Dyna Girl",
"Elliot from Earth",
"Emerald Soup ",
"Endō Akinori",
"Enterprise ",
"Ergo Proxy",
"Escaflowne ",
"Escape from Jupiter",
"Eureka",
"Event, The",
"Extant",
"Falconer ",
"Falling Skies",
"Fantastic Journey, The",
"Fantastic Voyage",
"Far Out Space Nuts",
"Farr, David",
"Farscape",
"Farscape: The Peacekeeper Wars ",
"Fearless Fly ",
"Final Space",
"Fire Next Time, The",
"Fireball XL5",
"Firefly",
"First Wave ",
"Flash, The",
"Flashforward",
"FLCL",
"Flintstones, The",
"Flip Flappers",
"Flipside of Dominick Hide, The",
"Fontana, D C",
"Foster's Home for Imaginary Friends",
"Foundation [series]",
"Fractale",
"Freakazoid!",
"Freiberger, Fred",
"Fringe",
"From the New World",
"Frost, Mark",
"Fullmetal Alchemist: Brotherhood",
"Fungies!, The",
"Fushigi-na Melmo ",
"Futurama",
"Future Boy Conan",
"Future Cop [tv]",
"Gainax",
"Galactic Patrol Lensman",
"Galactica: 1980",
"Galaxy Express 999",
"Galaxy High",
"Gargantia on the Verdurous Planet",
"Gemini Man ",
"Gene Roddenberry's Andromeda ",
"Genius Party",
"gen:LOCK",
"Gerry Anderson's New Captain Scarlet ",
"Get Smart!",
"Ghost and Molly McGee, The",
"Ghost in the Shell: Stand Alone Complex",
"Giant Robo",
"Gigantor ",
"Ginga Uchū Odyssey",
"Girl across Time ",
"Girl from Tomorrow, The",
"Girl from U.N.C.L.E., The ",
"Girl with Something Extra, The",
"Girls' Last Tour",
"Glitch Techs",
"Golan the Insatiable",
"Good Place, The",
"Goong",
"Goong S ",
"Goss, James",
"Granbelm",
"Gravity Falls",
"Greatest American Hero, The",
"Green Eggs and Ham",
"Green Hornet, The",
"Green Legend Ran",
"Greene, Joseph",
"Grim Adventures of Billy & Mandy, The",
"Gulliver",
"Gulliver's Travels ",
"Gundam ",
"Gundam Wing ",
"Gurren Lagann",
"Haibane Renmei",
"Hanna-Barbera",
"Hard Time on Planet Earth",
"Hare+Guu",
"Harley Quinn",
"Harsh Realm ",
"Haskin, Byron",
"Hazbin Hotel",
"He-Man and the Masters of the Universe ",
"Heat Vision and Jack",
"Heaven's Design Team",
"Hellsing",
"Helluva Boss",
"Henson, Jim ",
"Herculoids, The",
"Heroes [tv]",
"Hertzler, J G",
"Hide and Seek ",
"Highwayman, The",
"Hilda",
"Himitsu Sentai Gorenger",
"Hitch Hiker's Guide to the Galaxy, The",
"Hitchcock, Alfred",
"Hollow, The",
"Holmes and Yo-Yo",
"Homeboys in Outer Space",
"Honey, I Shrunk the Kids",
"House of Frankenstein",
"Human Kind Of",
"Humanity Has Declined",
"I Dream of Jeannie",
"Iannucci, Armando",
"Iczer One",
"I'll Be Back ",
"Immortal, The",
"Incredible Hulk, The",
"Infinity Train",
"Inhumanoids",
"Inside Job",
"Interviews with Monster Girls",
"Into Infinity ",
"Invader Zim",
"Invaders from the Deep ",
"Invaders, The",
"Invasion [tv]",
"Invasion America",
"Invasion: Earth [tv] ",
"Invincible",
"Invisible Man, The",
"Iron Man",
"Isis",
"It's About Time",
"Jake 2.0 ",
"Japanese Spider-Man",
"Jason of Star Command",
"Jekyll ",
"Jellystone!",
"Jeremiah",
"Jericho",
"Jessica Jones",
"Jessup, Richard",
"Jet Jackson, Flying Commando ",
"Jetsons, The",
"Joe 90",
"Johnny Jupiter",
"Johnny Sokko and His Flying Robot ",
"Johnson, Kenneth",
"Jolley, Norman",
"Jones, Terry",
"Jonny Quest",
"Jonny Quest: The Real Adventures ",
"Jonny Quest vs the Cyber Insects ",
"Jonny's Golden Quest ",
"Journey of Allen Strange, The",
"Journey Through the Black Sun ",
"Journey to the Center of the Earth",
"Journeyman",
"Jurasik, Peter ",
"Justice League",
"Justice League Unlimited ",
"Kaiba",
"Kamen Rider",
"Keep Your Hands Off Eizouken!",
"Kemono Friends",
"Kemurikusa",
"Kettering Incident, The",
"Kid Cosmic",
"Kids From C.A.P.E.R., The",
"Kill La Kill",
"Kim Possible",
"Kimagure Robot",
"Kimi to Ita Mirai no Tame Ni",
"Kino's Journey",
"Kinvig",
"Kipo and the Age of Wonderbeasts",
"Knight Rider",
"Knights of Sidonia",
"Kolchak: The Night Stalker",
"Korg: 70,000 BC",
"Koyama Takao",
"Kroft Super Show, The ",
"Kyousougiga",
"Ladd, Fred",
"Land of the Giants",
"Land of the Lost",
"Land of the Lustrous",
"Larson, Glen A",
"Lazor Wulf",
"Legend of Korra, The",
"Legends of the Superheroes",
"Lenkov, Peter M",
"Lester, Richard",
"Life after People",
"Life on Mars",
"Lights Out",
"Lilo & Stitch",
"Link Click",
"Little Lies We All Tell, The",
"Little Witch Academia",
"Livingston, Harold",
"Llewellyn, Robert",
"Logan's Run",
"Lois & Clark: The New Adventures of Superman",
"Lone Gunmen, The ",
"Looney Toons ",
"Lost",
"Lost in Space",
"Lost on Earth",
"Lost Planet, The",
"Lost Saucer, The",
"Love, Death and Robots",
"Lucan",
"Luke Cage",
"Lycoris Recoil",
"M.A.N.T.I.S.",
"M.D. Geist",
"McCracken, Craig",
"Mackie, Philip",
"Macnee, Patrick",
"Made in Abyss",
"Madhouse",
"Mama Wa Shōgaku Yon-Nensei",
"Man and the Challenge, The",
"Man from Atlantis, The",
"Man from U.N.C.L.E., The",
"Man Who Fell To Earth, The [tv]",
"Maniac",
"Maniac Mansion [tv]",
"Manimal",
"Mann and Machine",
"Mantley, John",
"Mao Mao: Heroes of Pure Heart",
"Martian Chronicles, The",
"Martian Successor Nadesico",
"Marvel Action Hour, The: Iron Man ",
"Marvel Super Heroes, The",
"Marvelous Misadventures of Flapjack, The",
"Mastermind ",
"Masters of Horror",
"Masters of Science Fiction",
"Masters of the Universe",
"Max Headroom",
"Mee's Forest",
"Melancholy of Haruhi Suzumiya, The",
"Men into Space",
"Mercy Point",
"Merrie Melodies ",
"Middleman, The",
"Midnight Gospel, The",
"Millennium [tv]",
"Milo Murphy's Law",
"Milton the Monster",
"Misfits ",
"Misfits of Science",
"Miss Kobayashi's Dragon Maid",
"Miss Kuroitsu from the Monster Development Department",
"Mission Galactica: The Cylon Attack ",
"Mister E from Tau Ceti",
"Mr Terrific",
"Mob Psycho 100",
"Mobile Police Patlabor",
"Mobile Suit Gundam",
"Mobile Suit Gundam: The Witch from Mercury",
"Monsters [tv]",
"Monty Python's Flying Circus",
"Moon Girl and Devil Dinosaur",
"Moonbase 3",
"Moore, Ronald D",
"Mōretsu Pirates",
"Mork & Mindy",
"MST 3000 ",
"MST3K ",
"Murder Drones",
"Mutant X",
"My Dad the Bounty Hunter",
"My Favorite Martian",
"My Hero Academia",
"My Life as a Teenage Robot",
"My Living Doll",
"My Love from the Star ",
"My Next Life as a Villainess: All Routes Lead to Doom!",
"My Secret Identity",
"Mystery Science Theater 3000",
"Mysticons",
"Nation, Terry",
"New Adventures of Jonny Quest ",
"New Adventures of Superman, The",
"New Adventures of Wonder Woman, The ",
"New Avengers, The ",
"New Batman/Superman Adventures, The ",
"New Captain Scarlet ",
"New Dream Hunter Rem ",
"New, Original Wonder Woman, The ",
"New People, The",
"New Tomorrow People, The ",
"Next Generation, The ",
"Nichijou",
"NieA Under 7",
"Night Gallery ",
"Night Man",
"Night Stalker",
"NightMan ",
"Noah's Castle ",
"Noein: To Your Other Self",
"Nowhere Man",
"OA, The",
"Occupert ",
"Occupied",
"OK K.O.! Let's Be Heroes",
"Once a Hero",
"One Punch Man",
"Onyx Equinox",
"Operation Neptune",
"Orbital Children, The",
"Ordinary Joe",
"Ordover, John J ",
"Oshii Mamoru",
"Otherside Picnic",
"Otherworld",
"Out of the Unknown",
"Out of This World",
"Out There",
"Outcasts ",
"Outer Limits, The",
"Outlaw Star",
"Outlaws",
"Over the Garden Wall",
"Owl House, The",
"Oz",
"Palin, Michael ",
"Pantheon",
"Parasite Dolls ",
"Parasyte -the maxim-",
"Parks and Recreation",
"Pemberton, Victor",
"Penguindrum",
"Phantom, The",
"Philip K Dick's Electric Dreams ",
"Phineas and Ferb",
"Phoenix, The",
"Piece of Phantasmagoria, A",
"Pinky & The Brain",
"Planet of the Apes",
"Planet Patrol ",
"Planet With",
"Planetarian: The Reverie of a Little Planet",
"Planetes",
"Pop Team Epic",
"Powerpuff Girls, The",
"Powers of Matthew Star, The",
"Pretty Guardian Sailor Moon ",
"Primal",
"Primeval ",
"Princess ",
"Princess Hours ",
"Princess Principal",
"Prisoner, The",
"Prisoners of Gravity",
"Probe [tv]",
"Project Blue Book ",
"Project G.e.e.K.e.R.",
"Project Sleepwalker ",
"Project UFO",
"Promised Neverland, The",
"Psycho-Pass",
"Puella Magi Madoka Magica",
"Puni Puni Poemy",
"Python, Monty ",
"Q.E.D.",
"Quantum Leap",
"Quark [tv]",
"Quatermass",
"Quatermass and the Pit",
"Quatermass Conclusion, The ",
"Quatermass Experiment, The",
"Quatermass II",
"Questor Tapes, The",
"Radiophonic Workshop ",
"Rascal Does Not Dream of Bunny Girl Senpai",
"Raumpatrouille: Die phantastischen Abenteuer des Raumschiffes Orion",
"Ray Bradbury Theater",
"Real Adventures of Jonny Quest, The ",
"Red Dwarf",
"Red Shift",
"Regular Show",
"Release the Spyce",
"Return of Captain Nemo, The ",
"Return of the Incredible Hulk ",
"Return to Jupiter",
"Return to the Lost Planet ",
"Return to the Planet of the Apes ",
"Revenge of the Mysterons from Mars ",
"Revolutionary Girl Utena",
"Rex the Runt",
"Re:Zero  Starting Life in Another World",
"Rick & Morty",
"RoboCop 3",
"RoboCop: The Series ",
"Robot Detective",
"Robotboy",
"Robotech ",
"Rocky Jones, Space Ranger",
"Rod Brown of the Rocket Rangers",
"Rod Serling's Night Gallery",
"Roddenberry, Gene",
"Roswell",
"Roughnecks: The Starship Troopers Chronicles ",
"RWBY",
"Sabikui Bisco",
"Saga of Tanya the Evil, The",
"Sailor Moon",
"Sale, David",
"Salvage 1",
"Samurai Jack",
"Sapphire and Steel",
"Sarah Jane Adventures, The",
"Saward, Eric",
"School-Live!",
"Sci Fi Channel, The ",
"Sci Fi Files, The",
"Science Fiction Theatre",
"Scott, Gavin",
"seaQuest 2032 ",
"seaQuest DSV",
"Search",
"Second Hundred Years, The",
"Secret Empire, The",
"Secret Files of Captain Video, The ",
"Secret Service, The ",
"Secret World of Alex Mack, The",
"Secrets of Isis, The ",
"Sense8",
"Serial Experiments Lain",
"Serling, Carol",
"Serling, Rod",
"Seven Days",
"Severance",
"Shadows House",
"Shagan, Steve",
"Shazam!",
"She-Ra and the Princesses of Power",
"Sheena ",
"Sheena, Queen of the Jungle",
"Sherlock Holmes in the 22nd Century",
"Sherlock Hound",
"Shimerman, Armin",
"Shinseiki Evangelion",
"Shirrefs, Mark",
"Short Circuit [tv]",
"Six Million Dollar Man, The",
"Sleepwalkers",
"Sliders",
"Sloman, Robert ",
"Small Wonder",
"Smallville",
"Snowbeast",
"Solar Opposites",
"Solid Geometry ",
"Something Is Out There",
"Sonny Boy",
"Space: 1999",
"Space 2063 ",
"Space: Above and Beyond",
"Space Academy",
"Space Cases",
"Space Command",
"Space Dandy",
"Space Ghost",
"Space Ghost and Dino Boy ",
"Space Maidens ",
"Space Patrol",
"Space Patrol Luluco",
"Space Pirate Captain Harlock",
"Space Precinct",
"Space Rangers [tv]",
"Space School",
"Space Stars ",
"SparkShorts",
"Special Duty Combat Unit Shinesman",
"Spellbinder",
"Spellbinder: Land of the Dragon Lord",
"Spider-Man [tv]",
"Spider-Man and His Amazing Friends",
"Spider-Woman",
"Spielberg, Steven",
"Spy X Family",
"Squid Girl",
"SS-GB ",
"SSSS.Dynazenon",
"SSSS.Gridman",
"Stand, The",
"Star Blazers ",
"Star Cops",
"Star Maidens",
"Star Trek",
"Star Trek: Deep Space Nine",
"Star Trek: Enterprise",
"Star Trek: Lower Decks",
"Star Trek: Picard",
"Star Trek: Prodigy",
"Star Trek: The Animated Series",
"Star Trek: The Next Generation",
"Star Trek: Voyager",
"Star vs the Forces of Evil",
"Star Wars: Clone Wars",
"Star Wars Visions ",
"Stargate: Atlantis",
"Stargate SG-1",
"Stargate: Universe",
"Starhunter",
"Starhunter 3200 ",
"Starlost, The",
"Steins;Gate",
"Stephen Hawking's Sci-Fi Masters ",
"Steven Spielberg's Amazing Stories ",
"Steven Universe",
"Sting of Death ",
"Stingray",
"Stop Susan Williams",
"Straczynski, J Michael",
"Strange New World",
"Strange World of Planet X, The",
"Stranger from Space ",
"Stranger Things",
"Street Hawk",
"Struck by Lightning",
"Studio Gainax ",
"Studio Trigger ",
"Sugar, Rebecca",
"Summer Camp Island",
"Super Dimension Century Orguss ",
"Super Dimensional Fortress Macross",
"Super Force",
"Super Friends",
"Super Friends II ",
"Super Sentai",
"Superboy",
"Supercar",
"Superman [character]",
"Superman and Scotland Yard ",
"Superman and the Jungle Devils ",
"Superman/Aquaman Hour, The ",
"Superman Flies Again ",
"Superman in Exile ",
"Superman: The Animated Series",
"Superman's Peril ",
"SuperMarionation",
"Supertrain",
"Surface",
"Survivors",
"Swamp Thing",
"Sweat Punch",
"Sweet Valerian",
"Syfy ",
"Sym-Bionic Titan ",
"Taken",
"Takt Op. Destiny",
"Talentless Nana",
"Tales from the Darkside",
"Tales of Tomorrow [tv/radio]",
"Tarasov, Vladimir",
"Tartakovsky, Genndy",
"Tarzan",
"Tarzan and the Super 7",
"Tarzan/Lone Ranger Adventure Hour, The",
"Tarzan, Lord of the Jungle",
"Tatami Galaxy, The",
"Technoroid Overmind",
"Tek War",
"Tek War: The Series ",
"Television",
"Television Anthology Series",
"Terminator: The Sarah Connor Chronicles",
"Terrahawks",
"Tetsujin 28 Go",
"Texhnolyze",
"They Came from Outer Space",
"Third Rock from the Sun ",
"Threshold",
"Thunderbirds",
"Tick, The",
"Tiger & Bunny",
"Time Express",
"Time Traveller ",
"Time Trax",
"Time Tunnel, The",
"Timeslip [tv]",
"Toki o Kakeru Shōjo",
"Tom Corbett: Space Cadet",
"Tomorrow People, The",
"Torchwood",
"Torchy the Battery Boy ",
"Toyota Aritsune",
"Treasure Island in Outer Space",
"Trese",
"Tribe, Steve ",
"Trigger",
"Trigun",
"Trollenberg Terror, The",
"Tuca and Bertie",
"Turn-On",
"Twelve Forever",
"Twilight Q",
"Twilight Zone, The",
"Uchū Michi e no Dai Kikou ",
"Uchū Senkan Yamato",
"UFO",
"Ultra Q",
"Ultraman",
"Ultraviolet",
"Undermind ",
"Undone",
"Uninvited, The ",
"Urusei Yatsura",
"V",
"V: The Final Battle ",
"Valley of the Dinosaurs",
"Vaughan, Brian K",
"Venture Bros, The",
"Video Girl Ai",
"Violet Evergarden",
"Viper",
"Visitor, The ",
"Vivy: Fluorite Eye's Song",
"Voltron: Legendary Defender",
"Voyage to the Bottom of the Sea",
"Voyager ",
"Voyagers",
"VR.5",
"W3 ",
"Walt Disney's Disneyland ",
"Wander over Yonder",
"War of the Worlds",
"Warehouse 13",
"Warner Bros. Cartoons",
"Watchmen [tv]",
"Watkins, Peter",
"'Way Out",
"Wednesday",
"Weird Science",
"Welcome to Paradox",
"Westworld [tv]",
"What a Cartoon!",
"What We Do in the Shadows",
"Where on Earth Is Carmen Sandiego?",
"Whitaker, David",
"Wild Palms",
"Wild, Wild West, The",
"Wonder 3, The",
"Wonder Egg Priority",
"Wonder Woman Film/TV",
"Wonderful Galaxy of Oz, The",
"Woops!",
"World of Beachcomber, The ",
"World of Giants",
"World War III",
"X [tv]",
"X-Files, The",
"Yamazaki Haruya",
"Yasuke",
"Year of the Sex Olympics, The",
"Yokohama Kaidashi Kikō",
"Yuasa Masaaki",
"Yukikaze",
"Yurei Deco",
"Yuri Kuma Arashi",
"Zandor ",
"Zombie Land Saga"]